- packages/rest-api-client/docs/record.md
> docs: add documentation for record.addRecord & record.updateRecord

- packages/rest-api-client/docs/record.md
> docs: record comment

- README.md
- packages/rest-api-client/README.md
Is there anything I should put on here?
> docs: update README.md on the root package

- packages/rest-api-client/README.md
- packages/rest-api-client/docs/errorHandling.md
- packages/rest-api-client/docs/record.md
- packages/rest-api-client/scripts/record.ts
- packages/rest-api-client/src/KintoneAllRecordsError.ts
- packages/rest-api-client/src/KintoneRestAPIClient.ts
- packages/rest-api-client/src/KintoneRestAPIError.ts
- packages/rest-api-client/src/__tests__/KintoneAllRecordsError.test.ts
- packages/rest-api-client/src/client/BulkRequestClient.ts
- packages/rest-api-client/src/client/RecordClient.ts
- packages/rest-api-client/src/client/__tests__/RecordClient.test.ts
> feat: implements addAllRecords.

- packages/rest-api-client/docs/record.md
- packages/rest-api-client/scripts/record.ts
- packages/rest-api-client/src/client/RecordClient.ts
- packages/rest-api-client/src/client/__tests__/RecordClient.test.ts
> feat: implement updateAllRecords

- packages/rest-api-client/README.md
- packages/rest-api-client/scripts/run-node.ts
- packages/rest-api-client/src/KintoneRestAPIClient.ts
- packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts
> feat: support OAuth token

- packages/rest-api-client/src/KintoneRestAPIClient.ts
- packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts
- packages/rest-api-client/src/platform/browser.ts
- packages/rest-api-client/src/platform/index.ts
- packages/rest-api-client/src/platform/node.ts
> feat: Add User-Agent header for Node.js

- .github/ISSUE_TEMPLATE/config.yml
> chore: Create config.yml to add contact links

- packages/rest-api-client/README.md
Fixes #265
use FQDN URLs instead of relative URLs.
Paste `README.md` at a markdown preview service and test if the links work correctly.
> docs: fix broken links on npmjs.com

- packages/rest-api-client/docs/file.md
Example code for Overview in file.md occurs syntax error.
Added `}` and format it.
Copy, paste, and execute it in your environment!!
> docs: fix syntax error for Overview code in file.md of rest-api-client

- packages/rest-api-client/src/client/RecordClient.ts
`record` arguments need `Record` type.
Can use `Record` type in calling `RecordClient`.
Modify existing `RecordClient` type test to `Record`.
> Attach type for record arguments.

- packages/rest-api-client/docs/typescript.md
- packages/rest-api-client/src/KintoneFields/exportTypes/__checks__/usecase-layout.ts
- packages/rest-api-client/src/KintoneFields/exportTypes/layout.ts
- packages/rest-api-client/src/KintoneFields/types/__checks__/layout.ts
- packages/rest-api-client/src/KintoneFields/types/fieldLayout.ts
- packages/rest-api-client/src/KintoneFields/types/layout.ts
> fix: export fields layout

- packages/plugin-packer/README.md
We've updated the URL of the `plugin-packer`'s website.
I've updated the URL of the `plugin-packer`'s website.
> docs: update a link to the website of plugin-packer

- packages/plugin-uploader/README.md
- packages/plugin-uploader/bin/cli.js
Description of options for plugin-uploader is different between README and what the program outputs.
Fix description of options that the program outputs 
1. build and run it
```
$ yarn
$ cd packages/plugin-uploader
$ yarn build
$ node bin/cli.js
```
2. check the output to correspond with README
> fix: description of Options for plugin-uploader

- .github/workflows/yamory.yml
I've created a GitHub Action to run yamory when a commit is pushed on the master branch.
See the result in the dashboard :)
> chore: run yamory on GitHub Actions

- CONTRIBUTING.md
We'll update the commit message format to include the target package as a scope.
I've updated the commit message format in `CONTRIBUTING.md`
> docs: add a scope into the commit message format

- packages/data-loader/src/parsers/__tests__/csvParser.test.ts
- packages/data-loader/src/parsers/__tests__/fixtures/fields.json
- packages/data-loader/src/parsers/__tests__/fixtures/output.json
- packages/data-loader/src/parsers/__tests__/fixtures/records.csv
- packages/data-loader/src/parsers/csvParser.ts
> feat(data-loader): support csv import

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/typescript.md
The word has various meanings, so we should avoid it.
I've updated to use `***` instead.
> chore: tweak issue templates

- packages/rest-api-client/docs/app.md
- In Table of Content, `updateGeneralNotifications` is missing.
- https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/app.md
- the index 
- insert `updateGeneralNotifications` into Table of Content
N/A
> docs(rest-api-client): insert `updateGeneralNotifications` into TOC

- .github/labeler-config.yml
- .github/workflows/labeler.yml
To triage the PRs with labels.
Add [actions/labeler](https://github.com/actions/labeler) to add labels automatically.
See [sample repository](https://github.com/shisama/monorepo-labeler-test/pull/3).
After merging, fix some packages and create PR.
> chore: add 'labeler' GitHub Actions

- .github/workflows/license.yml
- license-finder-decisions.yml
This introduces a new check for licenses of dependencies.
I've added a GitHub Actions and a rule file for the check.
> chore: add a GitHub Actions for license-finder

- packages/data-loader/src/controllers/import.ts
In data-loader, it imports a file using by `readFile()`.
If a file is too large, it is liable to occur a memory leak and decrease performance.
use ReadableStream instead of `readFile()`.
N/A
> refactor(data-loader): use ReadableStream instead of readFile

- packages/rest-api-client/src/KintoneRestAPIClient.ts
- packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts
Fix #917 
Validate guestSpaceId when creating `KintoneRestAPIClient` instance.
> fix(rest-api-client): validate guestSpaceId

- packages/create-plugin/templates/minimum/package.json.tmpl
- packages/create-plugin/templates/modern/package.json.tmpl
- packages/create-plugin/templates/modern/src/js/config.ts
The packages included in the templates of create-plugin haven't been updated for a while.
Update all dependencies in template projects.
```bash
$ cd packages/create-plugin
$ yarn
$ yarn build
$ node bin/cli.js <project name>
$ node bin/cli.js --template=modern <project name>
```
> feat(create-plugin): update all dependencies in template projects

- packages/dts-gen/kintone.d.ts
N/A
fix typo isShwon -> isShown
N/A
close https://github.com/kintone/js-sdk-ja/issues/25
> dts-gen:fix typo isShwon -> isShown

- packages/customize-uploader/src/messages.ts
- packages/plugin-uploader/src/messages.ts
> fix(customize-uploader,plugin-uploader): fix typo

- README.md
Thank you for your contribution!!
Add author and contributors to README
none
> chore(docs): Add author and contributors

- .github/workflows/yamory.yml
Yamory starts to provide checksum of their scripts.
It can detect script tampering.
announce: https://yamory.io/releases/202206/
docs: https://yamory.io/docs/verify-app-library-scan-script/
N/A
> chore: validate yamory script

- .github/workflows/license.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/version.yml
Because `--immutable` option is for yarn v3.
N/A
> ci: replace usage of `--immutable` to `--frozen-lockfile`

- .github/project.yml
To manage our issues and PRs on GitHub Project
https://github.com/kintone/cli-kintone/actions/runs/4200749081/jobs/7287081462
> ci: add workflow to add issues and PRs to project

- packages/rest-api-client/package.json
- packages/rest-api-client/src/platform/browser.ts
- yarn.lock
Fix #1939 
- Replace [mime-types](https://github.com/jshttp/mime-types) by [mime](https://github.com/topics/mine) package
N/A
> fix: replace mime-types by mime package

- yarn.lock
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
> chore: update caniuse-lite

- packages/customize-uploader/bin/cli.js
- packages/customize-uploader/src/commands/__tests__/import.test.ts
- packages/customize-uploader/src/commands/import.ts
- packages/customize-uploader/src/commands/index.ts
- packages/customize-uploader/src/messages.ts
- packages/dts-gen/package.json
- packages/dts-gen/src/integration-tests/dts-gen-api-test.ts
- packages/dts-gen/webpack.config.js
- pnpm-lock.yaml
- Fix Lint warning message
- Wrap arguments into object
- split to small function
- `pnpm lint` has no warning anymore.
- Run customize-uploader succesfully.
> refactor: Resolve Lint warning message

- .github/labeler-config.yml
- .github/workflows/labeler.yml
[labeler action](https://github.com/actions/labeler/) has upgraded to v5
N/A
> ci: update breaking changes of labeler v5

- packages/rest-api-client/src/client/RecordClient.ts
- packages/rest-api-client/src/client/__tests__/RecordClient.test.ts
- Fix the maximum call stack size exceeded error
- flattern the function using iteration instead of recursion
- TBD
> fix(rest-api-client): fixing maximum call stack size exceeded error

- packages/plugin-packer/package.json
- pnpm-lock.yaml
- It's no longer use in any place
- Remove it
- Check plugin-packer works normally
> chore(plugin-packer): remove unused package

- .github/ISSUE_TEMPLATE/10-bug-report.yml
- .github/ISSUE_TEMPLATE/20-feature-request.yml
- .github/ISSUE_TEMPLATE/config.yml
To make it clear where the suitable place to contact us is by the topic.
- update issue templates
N/A
> chore: update issue templates and template chooser

- .github/workflows/labeler.yml
- .github/workflows/license.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/yamory.yml
To visualize what CI step is the bottleneck.
Add https://github.com/Kesin11/actions-timeline
Check CI results
> ci: add actions-timeline for inspection

- examples/rest-api-client-demo/src/space.ts
- packages/rest-api-client/docs/space.md
- packages/rest-api-client/src/client/AbstractClient.ts
- packages/rest-api-client/src/client/AppClient.ts
- packages/rest-api-client/src/client/BaseClient.ts
- packages/rest-api-client/src/client/BulkRequestClient.ts
- packages/rest-api-client/src/client/FileClient.ts
- packages/rest-api-client/src/client/RecordClient.ts
- packages/rest-api-client/src/client/SpaceClient.ts
- packages/rest-api-client/src/client/__tests__/SpaceClient.test.ts
- Support deleteSpace API to be able to delete a space.
- Add new method `deleteSpace`
- Check test spec
> feat(rest-api-client): add `space.deleteSpace()` method

- examples/rest-api-client-demo/src/run-node.ts
- examples/rest-api-client-demo/src/space.ts
- packages/rest-api-client/docs/space.md
- packages/rest-api-client/src/client/SpaceClient.ts
- packages/rest-api-client/src/client/__tests__/SpaceClient.test.ts
- packages/rest-api-client/src/client/types/index.ts
- Support `updateSpaceGuests` method to be able to update the Guest Members of a Space.
- Add new method `updateSpaceGuests`
- Check test spec
> feat(rest-api-client): add `space.updateSpaceGuests()` method

- packages/rest-api-client/docs/space.md
The reference links are not updated
Update reference links
N/A
> docs(rest-api-client): Update reference links

- examples/rest-api-client-demo/package.json
- packages/rest-api-client/README.md
- Update docs with correct grammar
- update packages/rest-api-client/README.md
- N/A
> docs(rest-api-client): fix grammar of readme

- packages/create-plugin/__e2e__/e2e.test.ts
- Increase the reliability of create-plugin package.
- Add test case JsSdkTest-9
`pnpm test:e2e`
> test(create-plugin): add test case for JsSdkTest-9

- packages/create-plugin/__e2e__/e2e.test.ts
- Increase the reliability of create-plugin package.
- Add test case JsSdkTest-14
`pnpm test:e2e`
> test(create-plugin): add test case for JsSdkTest-14

- packages/plugin-manifest-validator/src/__tests__/index.ts
The test case failed due to a mismatch in the expected result.
- Update the expect result
```
pnpm test
```
> test(plugin-manifest-validator): update outdated expected result

- package.json
- pnpm-lock.yaml
- prevent the security issues from Dependabot
- use `overrides` setting to fix version of deps
N/A
> chore: fix security of deps

- release-please-config.json
https://github.com/kintone/cli-kintone/pull/866 に合わせてリリースPRのタイトルを変更した。
- 変更前: `chore: release main`
- 変更後: `chore: release from main`
> chore: update release PR title

- packages/plugin-packer/docs/index-ja.html
- packages/plugin-packer/docs/index.html
To analyze if https://plugin-packer.kintone.dev is still actively used today.
NOTE: The GA applied on this site is unmaintained, so we added a new GTM in this PR. ~We will delete the old GA after we confirm it's okay.~ We deleted the old GA.
- enable a GTM setting on https://plugin-packer.kintone.dev
- delete old GA settings
Check the rendered website.
> chore(plugin-packer): apply new GTM to website

- .github/workflows/release.yml
https://github.com/kintone/js-sdk/actions/runs/12683900654/job/35351750427
> ci: fix release workflow with Provenance

- packages/rest/src/__tests__/helpers/iterator.test.ts
- packages/rest/src/schemas/schema.d.ts
> chore(rest): update client ver.20250101000000

- .github/workflows/test-e2e.yml
- packages/rest/__e2e__/e2e.test.ts
- packages/rest/babel.config.js
- packages/rest/eslint.config.mjs
- packages/rest/jest.config.js
- packages/rest/jest.e2e.config.js
- packages/rest/package.json
- packages/rest/src/__tests__/helpers/iterator.test.ts
- packages/rest/src/schemas/schema.d.ts
> test(rest): Add e2e tests

- packages/rest/__e2e__/e2e.test.ts
- packages/rest/src/schemas/schema.d.ts
> chore(rest): Update schema.d.ts

- packages/rest/package.json
- packages/rest/scripts/copy-schemas.js
Improve build commands. 
- Implemented cross-platform schema file copy process
- Replaced `cp` command with Node.js `fs` module
- Created new `scripts/copy-schemas.js`
- Enhanced build commands
- Added `--force` option to `tsc --build`
- Added development watch mode script (`start`)
> chore(rest): Improve build commands

- packages/rest/src/client/KintoneClientOptions/index.ts
Rename the option: certAuth -> clientCertAuth
> fix(rest): certAuth -> clientCertAuth

- release-please-config.json
> chore: reenable release of rest.js

- .github/workflows/test-e2e.yml
https://github.com/stoplightio/prism/issues/2689
Temporarily downgrade prism to 5.12.0
> ci: Apply workaround for prism issue.

- license-manager.config.js
- packages/rest/package.json
- pnpm-lock.yaml
@kintone/rest@0.1.0 fails arethetypeswrong check.
https://arethetypeswrong.github.io/?p=%40kintone%2Frest%400.1.0
- updated exports field of packages.json
> fix(rest): fix exports field of package.json

- packages/rest/src/schemas/schema.ts
Update descriptions for records
> feat(rest): add description to schema.ts

- packages/rest/src/schemas/schema.ts
add description to file plugin
> feat: add description to file plugin

- packages/rest/src/schemas/schema.ts
> feat(rest): add description for spaces

- package.json
- packages/eslint-plugin/src/index.ts
- packages/plugin-packer/eslint.config.mjs
- packages/plugin-packer/site/dom.js
- packages/plugin-packer/site/eslint.config.mjs
- packages/plugin-packer/site/index.js
- packages/rest/__e2e__/e2e.test.ts
- packages/rest/__e2e__/setup.ts
- packages/rest/vitest.e2e.config.ts
Implementing mitigation measures against recent npm supply chain attacks
Update pnpm version before configuring minimumReleaseAge
pnpm fix
pnpm build:all
pnpm test
> chore: update pnpm

- pnpm-workspace.yaml
Implementing mitigation measures against recent npm supply chain attacks
Update pnpm version and configure minimumReleaseAge
Search for recently updated npm packages, configure minimumReleaseAge to span across release dates, run pnpm install, and verify that packages are not installed
> chore: set minimumReleaseAge

- .github/workflows/release.yml
> ci: install latest npm on release workflow
