package.json
To avoid running `build` when releasing.
=> build(package): run `lint` and `build` in `release`

packages/rest-api-client/README.md, packages/rest-api-client/src/KintoneRestAPIClient.ts, packages/rest-api-client/src/__tests__/KintoneAPIClient.test.ts
It would be better in the browser environment if we can omit `auth` param when creating APIClient object.
=> Make `auth` optional

.github/workflows/test.yml, packages/rest-api-client/package.json
BREAKING CHANGE: no longer support Node v8
=> chore: drop support Node v8

packages/rest-api-client/package.json
`jest src` includes unexpected test files when this repository directory path includes `src`.
=> chore: fix test command

packages/rest-api-client/src/KintoneRestAPIClient.ts, packages/rest-api-client/src/__tests__/KintoneAPIClient.test.ts
Add `basicAuth` option to KintoneRestAPIClient constructor to support Basic Authentication.
=> feat: add basicAuth to KintoneRestAPIClient

packages/rest-api-client/package.json
We should specify the `repository.directory` field in the `package.json` each monorepo packages.
https://github.com/renovatebot/renovate/issues/2926#issuecomment-575094237
It's a recommended way of npm.
https://docs.npmjs.com/files/package.json#repository
=> chore: fix the repository field of pacakge.json for monorepo support

packages/rest-api-client/src/client/RecordClient.ts
In the response type of `getRecordComments()`, `Comment.id` should be `string`.
=> fix: type definition of Comment.id

lerna.json
This would fix the issue https://github.com/kintone/js-sdk/pull/90#issuecomment-593561340.
The option affects `lerna bootstrap` command only, so I guess Renovate uses `lerna bootstrap` command internally.
https://github.com/lerna/lerna/blob/92f3c6691b8dd87227e85acdefef66662d49340d/commands/bootstrap/README.md#--use-workspaces
=> chore: add useWorkspaces option into lerna.json

packages/rest-api-client/src/KintoneAllRecordsError.ts, packages/rest-api-client/src/__tests__/KintoneAllRecordsError.test.ts
It seems `KintoneAllRecordsError.extractErrorIndex()` doesn't work correctly if `error.bulkRequestIndex = 0`.
=> fix: consider when error.bulkRequestIndex = 0

package.json, packages/customize-uploader/package.json, packages/rest-api-client/package.json, yarn.lock
`@type/node` and `@types/jest` are used in all packages so I'd like to hoist the dependencies to the root.
=> deps: hoist @types dependencies

packages/rest-api-client/jest.config.js, packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts
This is a part of #168 
Jest's default test environment is `jsdom`.
https://jestjs.io/docs/en/configuration#testenvironment-string
`rest-api-client` doesn't need `jsdom` as a unit test environment, so I disable the setting.
I've also removed a setup code depending on `jsdom`.
=> test(rest-api-client): disable jsdom for unit testing

packages/customize-uploader/jest.config.js
`customize-uploader` doesn't need `jsdom`.
See #169 for the detail.
=> test(customize-uploader): disable jsdom for unit testing

packages/customize-uploader/bin/cli.js, packages/customize-uploader/package.json
The current version of the `kintone-customize-uploader` command is broken due to the wrong require paths.
I'm not sure why it has happened.
But I want to fix this ASAP, so I've created a PR.
=> fix(customize-uploader): wrong require file paths in bin/cli.js

packages/rest-api-client/package.json
This PR is to add an npm-scripts to create `lib/*.js` files with a watch mode.
This is useful for type checking, and executing a script in `examples/rest-api-client-demo`.
Because when we use `@kintone/rest-api-client` in other packages, `lib/*.js`files are used, so we have to compile to use the latest version of `@kintone/rest-api-client`.
=> chore: add npm start

examples/rest-api-client-demo/README.md, examples/rest-api-client-demo/package.json, examples/rest-api-client-demo/tsconfig.json, yarn.lock
After #177  had been merged, we need to compile `rest-api-client` to run scripts in `rest-api-client-demo`.
In order to fix this, I've created a PR #182, but we still need to compile with this PR.
It's cumbersome, so I take another option, which is a way to use the `paths` compiler option.
In this PR, we can run scripts as `yarn script record getRecord` regardless of compiling `rest-api-client`, which is the same experience before #177.
=> build: use paths compiler option to run scripts without compiling

packages/rest-api-client/.eslintrc.js, packages/rest-api-client/src/KintoneRequestConfigBuilder.ts, packages/rest-api-client/src/KintoneRestAPIClient.ts, packages/rest-api-client/src/__tests__/KintoneRequestConfigBuilder.test.ts, packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/src/platform/index.ts, packages/rest-api-client/src/platform/node.ts
move 'buildAuth', 'buildHeader', 'buildParams' from KintoneRestAPIClient
to KintoneRequestConfigBuilder.
=> refactor: move functions which create request config to KintoneRequestConfigBuilder

packages/rest-api-client/README.md, packages/rest-api-client/src/KintoneRequestConfigBuilder.ts, packages/rest-api-client/src/__tests__/KintoneRequestConfigBuilder.test.ts, packages/rest-api-client/src/http/AxiosClient.ts, packages/rest-api-client/src/http/HttpClientInterface.ts, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/src/platform/index.ts, packages/rest-api-client/types/global/index.d.ts
I would like to use this SDK in Garoon JavaScript customize.
But now, it's not supported to send request with request token getting by Garoon JavaScript API.
So I made this PR to support it.
Please review and merge!!!
cf. [kintone連携用トークンを取得する - cybozu developer network](https://developer.cybozu.io/hc/ja/articles/115005294843-kintone%E9%80%A3%E6%90%BA%E7%94%A8%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B)
=> feat: support `garoon.connect.kintone.getRequestToken()` of Garoon JavaScript API

.github/ISSUE_TEMPLATE/config.yml
Current url for Japanese people is not canonical.
Remove the trailed slash.
=> chore: canonicalize kintone/js-sdk-ja URL

packages/plugin-manifest-validator/package.json, yarn.lock
To reduce installed packages.
Removed packages defined in the root `package.json` from `package.json` of `plugin-manifest-validator` 
`yarn test` and `yarn lint`
=> chore: remove common devDependencies from manifest-validator

packages/rest-api-client/src/KintoneRestAPIClient.ts, packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/src/platform/index.ts, packages/rest-api-client/src/platform/node.ts
RestAPIClient gets a `baseUrl` from `location.origin` in a browser environment if `baseUrl` is not specified, which is a function depends on a browser environment.
I've extracted the function as a platform dependency.
`yarn lint` && `yarn test`
=> refactor: add buildBaseUrl as a platform deps

packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/types/global/index.d.ts
IE11 doesn't provide `location.origin` in some cases.
https://stackoverflow.com/questions/32722032/how-does-ie11-populate-window-location-origin
use `location.protocol` and `location.host` instead of `location.origin`
`yarn test` and `yarn lint`
=> fix: use location.{protocol, host} instead of location.origin

packages/rest-api-client/src/client/RecordClient.ts
In`RecordClient#getAllRecordsWithCursor()`, occurring an error  will not guarantee to delete the cursor.
If a process is killed unintentionally, the cursor has remained until the expiration.
Change to throw exception after wait to delete the cursor if exception is throws in `RecordClient#getAllRecordsWithCursor()`.
`yarn test` and `yarn lint`
=> fix: need to wait response to delete cursor in `getAllRecordsWithCursor`

packages/rest-api-client/src/client/__tests__/AppClient.test.ts, packages/rest-api-client/src/client/__tests__/BulkRequestClient.test.ts, packages/rest-api-client/src/client/__tests__/File.test.ts, packages/rest-api-client/src/client/__tests__/RecordClient.test.ts, packages/rest-api-client/src/http/MockClient.ts
`MockClient` has not used `KintoneRequestConfigBuilder` like as `AxiosClient`.
- Change the interface of `MockClient` like as `AxiosClient`, and fix tests.
`yarn test` and `yarn lint`
=> refactor: use `KintoneRequestConfigBuilder` in `MockClient`

packages/customize-uploader/package.json
We don't want to publish the previous build assets to npm because it causes an unintentional behavior.
I've added `clean` npm-scripts into `customize-uploader` as well as `rest-api-client` does.
`yarn build`
=> chore: add clean npm-script

packages/rest-api-client/babel.config.js, packages/rest-api-client/webpack.config.js
In Prettier v2.0, default value of `trailingComma` became `true`.
ref. https://prettier.io/blog/2020/03/21/2.0.0.html
Apply Prettier to  javascript files about configuration in `@kintone/rest-api-client`.
`yarn lint` && `yarn test`
=> style: apply prettier to `@kintone/rest-api-client`

packages/rest-api-client/README.md, packages/rest-api-client/src/KintoneRestAPIClient.ts, packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/src/platform/index.ts, packages/rest-api-client/src/platform/node.ts, packages/rest-api-client/types/global/index.d.ts, packages/rest-api-client/webpack.config.js
I want to get the version of RestAPIClient even when use UMD builds.
This PR is based on #272 
Add a version property as a static property.
```javascript
KintoneRestAPIClient.version
// "1.4.2"
```
`yarn lint` && `yarn test`
=> feat: add a version property into KintoneRestAPIClient

packages/customize-uploader/package.json, yarn.lock
[@types/chokidar](https://www.npmjs.com/package/@types/chokidar) is now deprecated.
Remove `@types/chokidar` from `customi-uploader`
=> chore: remove @types/chokidar because of the deprecation

packages/rest-api-client/src/platform/__tests__/browser.test.ts, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/types/global/index.d.ts
An error occurred while attempting to request except `GET` in a Garoon environment.
`kintone` object does not exist in a Garoon environment, so throws `ReferenceError`.
The first thing, check a type of `kintone` (and `garoon`)  whether its type is `object`.
`yarn run lint` && `yarn test`
=> fix: fix a order to check kintone/garoon object

.eslintrc.js, package.json, packages/create-plugin/.eslintrc.js, packages/customize-uploader/.eslintrc.js, packages/plugin-manifest-validator/.eslintrc.js, packages/plugin-packer/.eslintrc.js, packages/profile-loader/.eslintrc.js, packages/rest-api-client/.eslintrc.js, yarn.lock
We want to use the latest version of @cybozu/eslint-config.
This is an alternative for #269 
I've updated @cybozu/eslint-config to v11, and unified `.eslintrc.js` for all pacakges except `plugin-packer`.
(`plugin-packer` has not been migrated to TypeScript)
I've disabled `@typescript-eslint/ban-types` for `{}` and `object` because we are using the types in many places, so we'll deal with the types as separated issues.
`yarn lint`
=> Update @cybozu/eslint-config  to v11

packages/rest-api-client/src/client/AppClient.ts, packages/rest-api-client/src/client/__tests__/AppClient.test.ts
checks type of Layout when the method argument takes `layout`.
- attach `LayoutForParaemeter` type to the method's parameter.
- fix test and add layout variation.
`yarn test`
=> refactor: attach type of Layout to method argument

renovate.json
Renovate does not manage dependencies in `examples/**` directory.
I'd like to that renovate updates packages in this directory similar to `packages/**`.
See #211
This repository's configuration extends `@cybozu/renovate-config`.
`@cybozu/renovate-config` has a preset as `:ignoreModulesAndTests` (ref. https://github.com/cybozu/renovate-config/blob/master/package.json#L23).
This preset ignores `package.json` in `examples` directory (ref. https://docs.renovatebot.com/presets-default/#ignoremodulesandtests) .
So this PR is that overwrites `ignorePaths` as not to ignore `examples` directory.
`renovate-config-validator`
Ref. https://docs.renovatebot.com/reconfigure-renovate/#reconfigure-via-pr
=> chore: manage `examples/*` by renovate

packages/rest-api-client/package.json
Using rest-api-client with UMD build file, KintoneRestAPIClient.version shows old version.
For example, When we use @kintone/rest-api-client@1.5.0, UMD file shows `1.4.2` running `KintoneRestAPIClient.version`.
see https://unpkg.com/@kintone/rest-api-client@1.5.0/umd/KintoneRestAPIClient.js
The reason why we make such a mistake is below.
KintoneRestAPIClient.version refers to packageJson.version. Actually, we inject the version into UMD file with webpack. https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/webpack.config.js#L33
We update version in package.json and publish the package after building UMD file with webpack.
The solution is just adding 'prepublish' command into rest-api-client/package.json.
We need to build UMD file after updating version in package.json. …
=> fix: KintoneRestAPIClient.version differs between UMD files and npm

packages/create-plugin/templates/modern/package.json.tmpl
We've released a new template called `modern` in the `create-plugin` package. 
But the `npm start` isn't succeed at the first time. The reason is that running `uploader` at the first time doesn't have target files created by `webpack` because the script run `webpack` and `uploader` parallel.
I've added `prebuild` script to run `webpack` before `npm start`.
```
% yarn build
% yarn create-plugin --template modern ~/target/dir
% cd ~/target/dir
% npm start
:
```
=> fix: `npm start` with the modern template

packages/customize-uploader/package.json, packages/customize-uploader/src/KintoneApiClient.ts, packages/customize-uploader/src/commands/__tests__/MockKintoneApiClient.ts, packages/customize-uploader/src/commands/index.ts, yarn.lock
[request-promise](https://github.com/request/request-promise) has already deprecated. 
It is replaced with `@kintone/rest-api-client`.
```bash
$ cd examples/rest-api-client-demo
$ yarn deploy
```
=> refactor: replace request-promise with @kitnone/rest-api-client

packages/create-plugin/tsconfig.json, packages/create-plugin/types/global/index.d.ts, packages/rest-api-client/types/global/index.d.ts, packages/webpack-plugin-kintone-plugin/tsconfig.json, packages/webpack-plugin-kintone-plugin/types/global/index.d.ts
To avoid an error of @types/puppeteer. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24419
Errors occur in https://github.com/kintone/js-sdk/pull/401.
Element type definition is added.
`yarn lint` & `yarn test`
=> fix: add Element type definition to avoid an error of @types/puppeteer

packages/rest-api-client/package.json
We run the `build` script at `prepublishOnly`, but we also have to run the script at `prelease` for pacakges depend on `rest-api-client` in js-sdk.
Otherwise, we cannot guarantee using the latest build of `rest-api-client` with these packages.
I've added the `build` script at prerelease stage.
=> chore: run the build script for packages depend on rest-api-client

examples/rest-api-client-demo/package.json, yarn.lock
In `examples/kintone-rest-api-client-demo`
In webpack.config.js, `webpack` uses ts-loader but `ts-loader` does not exist in dependency.
ref: https://github.com/kintone/js-sdk/blob/master/examples/rest-api-client-demo/webpack.config.js#L21
Therefore, execute `yarn deploy`, then fail to build customized files.
add `ts-loader` to dependency
`yarn deploy`
=> fix: kintone-rest-api-client-demo requires ts-loader at deploy

packages/rest-api-client/package.json, packages/rest-api-client/src/__tests__/KintoneRequestConfigBuilder.test.ts, yarn.lock
https://github.com/kintone/js-sdk/pull/319 upgrades js-base64 to v3. However,  js-base64 v3 doesn't support IE 11.
https://github.com/dankogai/js-base64/blob/96b271eb23441d3a48430b59b5d481db08674f5f/README.md#heads-up 
So this reverts js-base64 to v2.
revert #319 
`yarn lint && yarn test`
=> fix(deps): revert js-base64 to v2

packages/rest-api-client/index.mjs, packages/rest-api-client/package.json
The alternative to #387
Simple ESM file `index.mjs` is added. And `"exports"` field is added into package.json to support Dual Package (ESM/CJS)
Create the ESM file and run it, please.
```js
import { KintoneRestAPIClient } from "@kintone/rest-api-client";
console.log(KintoneRestAPIClient.version);
```
=> feat: support Node.js native ESM for rest-api-client

packages/dts-gen/README.md, packages/dts-gen/docs/maintenance-guide.md
We no longer host the documentations for `dts-gen` on GitHub Pages.
I've updated the links of documentations for `dts-gen` from hosted pages to markdown files.
=> docs: update links for the documentations of dts-gen

packages/rest-api-client/src/KintoneFields/types/layout.ts, packages/rest-api-client/src/client/types/app/form.ts
Although the `Layout` type definition is located in KintoneFields/types/layout.ts and exported from the file, this type is not exported externally(just be used in the definition of `KintoneRestAPIClient`).
It is inappropriate to locate type definitions like this in there.
I move this definition to client/types/app/form.ts.
`yarn lint` & `yarn test`
=> refactor: move the type definition for Layout

packages/rest-api-client/src/KintoneRequestConfigBuilder.ts, packages/rest-api-client/src/KintoneRestAPIClient.ts, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/src/platform/index.ts, packages/rest-api-client/src/types/auth.ts
Type definitions for authentication object are located in KintoneRestAPIClient.ts.
However, since these definitions are independent from the definition of `KintoneRestAPIClient`,  they should be located in another file.
Actually, a circular reference occurs between KintoneRestAPIClient.ts and KintoneRequestConfigBuilder.ts because `KintoneRequestConfigBuilder` refers them.
I create a new file to locate them & move them to there.
`yarn test` & `yarn lint`
=> refactor: move type definitions for auth

packages/rest-api-client/src/client/RecordClient.ts, packages/rest-api-client/src/client/__tests__/RecordClient.test.ts
Fixes https://github.com/kintone/js-sdk-ja/issues/3
I shift the timing to show the warning about maximum offset value after the request to get records has done.
Because the request sent to an environment which has already been applied the maximum offset value limitation will be fail, in the case, the warning are not be shown.
`yarn test & yarn lint`
=> fix: change the timing to show the warning for large offset

packages/rest-api-client/README.md
@kintone/rest-api-client supports multiple browsers, however, it has not listed in a document.
I added a descrption about browser supports to `README.md` based on [rollup.config.js](https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/rollup.config.js)
yarn lint
=> docs: write browser supports for rest-api-client

examples/rest-api-client-demo/src/app.ts, packages/rest-api-client/src/client/AppClient.ts, packages/rest-api-client/src/client/__tests__/AppClient.test.ts
AppClient needs properties type for parameter.
Because as it stands now, the parameter isn't being suggested properties.
Add type definition for properties as the parameter.
As a trade-off for suggesting a property, you need to specify "as const" for the property "types"
example
```ts
const properties = {
fieldCode: {
type: "SINGLE_LINE_TEXT" as const,
code: "fieldCode",
label: "Text Field",
},
};
appClient.updateFormFields({ app, properties, revision });
```
Existing
=> fix: Modify `properties` type in AppClient

packages/dts-gen/docs/how-to-use.md, packages/dts-gen/src/createCommanderProgram.test.ts, packages/dts-gen/src/createCommanderProgram.ts, packages/dts-gen/src/index.ts
This is a part of #530 
This PR is based on #458 (Thank you @potaracom 👏 ).
I've added the following environment variables support in `dts-gen`
- `KINTONE_USERNAME`
- `KINTONE_PASSWORD`
- `KINTONE_BASIC_AUTH_USERNAME`
- `KINTONE_BASIC_AUTH_PASSWORD`
I'll add other environment variables support in other PRs.
=> feat: support environment variables for user authentication of dts-gen

packages/plugin-uploader/README.md, packages/plugin-uploader/bin/cli.js, packages/plugin-uploader/src/index.ts, packages/plugin-uploader/src/messages.ts, packages/plugin-uploader/src/params.ts
I've added an environment variable and a CLI flag support in plugin-uploader.
- `KINTONE_BASE_URL`
- set `KINTONE_BASE_URL`to environment valiable and execute `bin/cli.js SAMPLE_PLUGIN.zip`
- execute `bin/cli.js SAMPLE_PLUGIN.zip` with `--base-url` option
=> feat: support environment variable for base URL of plugin-uploader

packages/plugin-uploader/src/params.ts
In #534, `plugin-uploader` has supported base-url option.
Although a user specifies `--domain`, `plugin-uploader` asks about baseURL.
Validate the value of optional domain, too.
`yarn build` & Execute `bin/cli.js SAMPLE_PLUGIN.zip --domain example.cybozu.com`.
=> fix: should not ask base-url if use domain option of plugin-uploader

packages/customize-uploader/README.md, packages/customize-uploader/bin/cli.js, packages/customize-uploader/src/messages.ts, packages/customize-uploader/src/params/index.ts
This is a part of #530 
I've added an environment variable and a CLI flag support in customize-uploader.
- `KINTONE_BASE_URL`
- set `KINTONE_BASE_URL` to the environment variables and run `bin/cli.js sample/customize-manifest.json`
- execute the following commands with `--base-url` option.
- `bin/cli.js sample/customize-manifest.json`
- `bin/cli.js import sample/customize-manifest.json`
=> feat: support environment variable for base URL of customize uploader

packages/customize-uploader/README.md, packages/customize-uploader/bin/cli.js, packages/customize-uploader/src/KintoneApiClient.ts, packages/customize-uploader/src/commands/__tests__/MockKintoneApiClient.ts, packages/customize-uploader/src/commands/__tests__/import.test.ts, packages/customize-uploader/src/commands/__tests__/index.test.ts, packages/customize-uploader/src/commands/import.ts, packages/customize-uploader/src/commands/index.ts, packages/customize-uploader/src/params/index.ts
- add `--oauth-token` option and support the `KINTONE_OAUTH_TOKEN` environment value.
- support authorization using an OAuth access token.
1. specify the following scopes and generate OAuth access tokens:
- for upload
- k:file:write
- k:app_settings:read
- k:app_settings:write
- for import
- k:file:read
- k:app_settings:read
1. build and run it.
```shell
$ yarn
$ cd packages/customize-uploader
$ yarn build
$ node bin/cli.js sample/customize-manifest.json --oauth-token YOUR_OAUTH_ACCESS_TOKEN_FOR_UPLOAD
$ node bin/cli.js import sample/customize-manifest.json --oauth-token YOUR_OAUTH_ACCESS_TOKEN_FOR_IMPORT
```
=> feat: support OAuth token of customize uploader

packages/dts-gen/docs/how-to-use.md, packages/dts-gen/src/cli-parser.ts, packages/dts-gen/src/integration-tests/setup-test-app.ts, packages/dts-gen/src/kintone/clients/axios-utils.test.ts, packages/dts-gen/src/kintone/clients/axios-utils.ts, packages/dts-gen/src/kintone/clients/forms-client-impl.test.ts
This is a part of #530.
I've added `HTTPS_PROXY` and `HTTP_PROXY` support in `dts-gen`.
In addition, I've added the `--proxy` option.
`proxyHost` and `proxyPort` are inconsistent with other packages like `customize-uploader` and `plugin-uploader`.
I'll deprecate these command line options in the future.
=> feat: support HTTP(S)_PROXY and --proxys option  in dts-gen

packages/rest-api-client/package.json
package.json of @kintone/rest-api-client cannot be imported like the following code due to #214.
It may break the build system of React Native or so on.
ref: https://github.com/nodejs/node/issues/33460
```javascript
const pkg = require("@kintone/rest-api-client/package.json");
// Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" 
```
package.json is added into the "exports" field in package.json of rest-api-client.
To check added code.
1. checkout this pull request
2. Run `npm link` in js-sdk/packages/rest-api-client directory
3. Run `npm link @kintone/rest-api-client` in the directory you want to try
4. Run `node -p 'require("@kintone/rest-api-client/package.json");'`
To check regression:
1. checkout this pull request
2. Run `npm link` in …
=> fix: add package.json into pkg.exports of rest-api-client

packages/plugin-packer/package.json, yarn.lock
webpack-dev-server@3.11.1 is released to fix the vulnerability. ref: https://github.com/webpack/webpack-dev-server/releases/tag/v3.11.1
plugin-packer has used webpack-dev-server@3.11.0, so it should be updated to 3.11.1.
Update 3.11.0 to 3.11.1.
- Install packages & run webpack-dev-server
```
$ yarn
$ yarn workspace @kintone/plugin-packer site:dev
```
- Open the page http://localhost:8080/
- Upload some plugin directory to the page
=> fix(deps): update webpack-dev-server to 3.11.1 to fix vulnerability

packages/rest-api-client/docs/errorHandling.md, packages/rest-api-client/index.mjs, packages/rest-api-client/src/__tests__/index.browser.test.ts, packages/rest-api-client/src/__tests__/index.test.ts, packages/rest-api-client/src/error/index.ts, packages/rest-api-client/src/index.browser.ts, packages/rest-api-client/src/index.ts
This allows users to import error classes like KintoneRestAPIError so that they can use them to check which error like the following code and to do other things.
```javascript
import { KintoneRestAPIClient, KintoneRestAPIError } from "@kintone/rest-api-client";
try {
const client = new KintoneRestAPIClient(baseUrl, auth);
const records = client.record.getRecord({ app, id });
// do something with the records variables
} catch (e) {
if (e instanceof KintoneRestAPIError) {
// do something if the error is KintoneRestAPIError
}
}
```
Classes in `src/error` are exported as a named export in index.ts or some entry points.
```
yarn test
```
=> feat: export error classes to allow users to import them

packages/plugin-uploader/src/index.ts
waitFor has been deprecated in puppeteer.
See https://github.com/puppeteer/puppeteer/issues/6214
=> fix: Fixed deprecated waitFor ()

.github/workflows/lint.yml, .github/workflows/test.yml
Currently, Renovate doesn't work as I expected. The reason is that we only run GItHub Actions for branches that has a PR, which causes a pending commit status and Renovate skips creating a PR due to the status.
I've changed to run GitHub Actions for branches that Renovate creates.
- [x ] Read [CONTRIBUTING.md](https://github.com/kintone/js-sdk/blob/master/CONTRIBUTING.md)
- [] Updated documentation if it is required.
- [] Added tests if it is required.
- [] Passed `yarn lint` and `yarn test` on the root directory.
=> ci: run GitHub Actions for branch push by Renovate

packages/customize-uploader/README.md, packages/customize-uploader/bin/cli.js, packages/customize-uploader/src/messages.ts, packages/customize-uploader/src/params/index.ts
- print a warning message if user specifies `--domain` or `KINTONE_DOMAIN`.
- In interactive CLI, ask base-url instead of domain
- execute `bin/cli.js dest/customize-manifest.json` with `--base-url` option or `KINTONE_DOMAIN`
- execute `bin/cli.js dest/customize-manifest.json` without setting of kintone environment
=> chore: print a warning message about deprecated of customize uploader

packages/plugin-manifest-validator/package.json
Maybe `ts-node` and` rimraf` do not have to be in the `dependencies` of plugin-manifest-validator.
`@types/bytes` should be in the `devDependencies`, not `dependencies`
- Remove `ts-node` and `rimraf` from `dependencies`.
- Move `@types/bytes` to `devDependencies` from `dependencies`.
=> chore: clean dependencies for plugin-manifest-validator

packages/rest-api-client/README.md
Since README is displayed in [npm package's page](https://www.npmjs.com/package/@kintone/rest-api-client),
it's useful for users to add short description on top of README so that they can quickly know what this library is.
Added short description on top of README
=> docs: add short description of rest-api-client on README

packages/data-loader/src/__tests__/main.test.ts
Test for data-loader fails if it is not built.
main.test.ts is fixed to run `npm run build` before tests in the test suite"
```
yarn test
```
=> test: run build script before tests in main.test.ts of data-loader

packages/plugin-manifest-validator/babel.config.js, packages/plugin-manifest-validator/package.json, packages/plugin-manifest-validator/src/index.ts, packages/plugin-manifest-validator/tsconfig.json, yarn.lock
Because it's Nodejs API is inconvenient when using from TypeScript.
Generate and ship type definition file via `declaration` option in `tsconfig.json`.
=> feat(plugin-manifest-validator): Generate declaration file for TS interface

README.md
data-loader has already been published. That's why the data-loader can be listed in root README.
The link for the data-loader directory is added to root README.
```
yarn lint
```
=> docs: add data-loader to root README

packages/data-loader/README.md
The default value for the `--password` option indicated in README is incorrect.
Also, the `--api-token` option is not listed in README even though it exists as an option.
The default value for the `--password` option in README was fixed.
The `--api-token` option was listed.
```
$ yarn lint
```
=> docs(data-loader): options in data-loader's readme

packages/plugin-manifest-validator/manifest-schema.json, packages/plugin-manifest-validator/src/index.ts
**BREAKING CHANGE: bump the JSON Schema version from draft4 to draft7**
`ajv` has dropped the support for JSON Schema draft4, so we have to update the version.
https://ajv.js.org/
I'v updated the version from `draft4` to `draft7`.
=> refactor: update JSON Schema version from draft4 to draft7

packages/data-loader/package.json, packages/data-loader/src/controllers/export.ts, yarn.lock
For performance reason, we want to avoid downloading attachments concurrently.
- Create a Kintone app, insert records, and upload attachments to some of the records
- Run the following commands:
```zsh
$ yarn build
$ node cli.js export --app=<APP_ID> --attachment-dir=foo # and username, password, base-url
```
- Then check the attachments are downloaded
=> chore(data-loader): download attachments sequentially

.github/workflows/yamory.yml
After #671 has been merged, Yamory starts failing because I've added `tsconfig.json` for the TypeScript Project References into the `packages/`.
- I've fixed the GitHub Actions to filter out the `tsconfig.json`.
- I've allowed to run Yamory for branches have the `yamory-` prefix for testing the GitHub Actions.
You can run Yamory on your local machine or see the result of GitHub Actions for this PR.
https://github.com/kintone/js-sdk/runs/1915165528
=> chore: fix target files for Yamory

packages/data-loader/README.md, packages/data-loader/src/commands/export.ts, packages/data-loader/src/commands/import.ts
Fix #701 
add defaultDescription properties into the options.
Open terminal and run the following command.
```
$ yarn start
```
Open another terminal and run the following commands.
```
$ node ./cli.js export --help
```
To show the help descriptions for import command, run the following commands.
```
$ cd packages/data-laoder
$ node ./cli.js import --help
```
Finally, please check if actual default values are not shown in the help description.
=> fix(data-loader): add defaultDescription to hide actual default value

packages/plugin-uploader/README.md, packages/plugin-uploader/bin/cli.js, packages/plugin-uploader/src/messages.ts, packages/plugin-uploader/src/params.ts
- print a warning message if user specifies `--domain` or `KINTONE_DOMAIN`.
- In interactive CLI, ask base-url instead of domain
- execute `bin/cli.js` PLUGIN.zip`
=> feat(plugin-uploader): print a deprecated message with warning

.github/workflows/compile-data-loader-binary.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Ref. #733
- Update CI settings.
- Add Node.js v14: test
- Update v12 to v14: lint and compile data-loader-binary
N/A
=> chore: add Node.js 14.x as a target version on CI

examples/rest-api-client-demo/src/app.ts, packages/rest-api-client/src/client/__tests__/AppClient.test.ts, packages/rest-api-client/src/client/types/app/notification.ts
Fixes #728 
- removes prop `notifications[].notifyToCommenter` from `updateGeneralNotifications`
- fixes tests `updateAppUpdateGeneralNotifications` and `updatePerRecordNotifications` (`AppClient.test.ts`)
- fixes demo script  `updateGeneralNotifications`
```sh
% yarn build
% yarn test
% yarn lint
% cd examples/rest-api-client-demo
% yarn run-script app updateGeneralNotifications
```
=> fix(rest-api-client): remove unnecessary props from Notification APIs

packages/rest-api-client/src/client/RecordClient.ts, packages/rest-api-client/src/client/__tests__/RecordClient.test.ts
Fixes #716 .
Enclose `condition` parameter of `getAllRecords()` and `getAllRecordsWithId()` with parenthesis (`()`). (See e634fb4)
NOTE: I didn't enclose the `conditionit` parameter of `getAllRecordsWithOffset()`.
1. Create a kintone app, insert more than 500 records
2. Call `getAllRecords()` with `condition` parameter that meets the following conditions:
- `condition` contains `or` clause (e.g. `'Customer != "foo" or Status in ("Completed")'` )
-  the number of filtered records also exceeds 500 records
3. Confirm that all expected records are returned, and the process finishes correctly
You can test it easily using [`getAllRecords()` demo script](https://github.com/kintone/js-sdk/blob/%40kintone/rest-api-client%401.10.0/examples/rest-api-client-demo/src/record.ts#L161) with modified …
=> fix(rest-api-client): prevent infinite loop when `condition` contains OR clause

packages/rest-api-client/src/client/types/app/notification.ts
According to the documentation, hoursLater and time appear to be returned exclusively in the response as well as the Request.
Also, being compatible with the request type means that the response can be passed to the request.
=> fix(rest-api-client): fix ReminderNotificationForResponse type

packages/data-loader/README.md
From [yargs v16.0](https://github.com/yargs/yargs/blob/master/CHANGELOG.md#1600-2020-09-09), single character aliases have been shown first in help output.
Adjust options of README.md to help output.
N/A
=> docs(data-loader): adjust options in README.md

packages/customize-uploader/src/KintoneApiClient.ts
`@kintone/customize-uploader` can not  apply customize to an app in a guest space.
Refer to https://github.com/kintone/js-sdk/issues/792.
`guestSpaceId` pass to `KintoneRestAPIClient`
```shell
yarn install
cd packages/customize-uploader
yarn build
bin/cli.js sample/customize-manifest.json --guest-space-id GUEST_SPACE_ID
```
=> fix(customize-uploader): pass guestSpaceId to KintoneRestAPIClient

packages/create-plugin/templates/minimum/package.json.tmpl, packages/create-plugin/templates/modern/package.json.tmpl
Dependencies in projects generated by `create-plugin` are outdated, so I'd like to update the versions to the latest.
I think the `package.json` should be managed by Renovate, so I'll work on that in the future.
I've bumped the versions for the dependencies to the latest versions.
You can create a project by the following commands.
```shell
node packages/create-plugin/bin/cli.js ${target}
// modern template
node packages/create-plugin/bin/cli.js ${target} --template modern
```
=> feat(create-plugin): update all dependencies in scaffolding projects

packages/data-loader/README.md, packages/data-loader/src/__tests__/main.test.ts, packages/data-loader/src/commands/export.ts, packages/data-loader/src/commands/import.ts, packages/data-loader/src/controllers/export.ts
In this PR, I added type and requirement information of arguments to CLI help message.
```sh
$ yarn build
$ node ./cli.js export --help
$ node ./cli.js import --help
$ node ./cli.js export
```
<details>
before
```sh
node ./cli.js export --help
cli.js export
export the records of the specified app
Options:
--version              Show version number                       [boolean]
--help                 Show help                                 [boolean]
--base-url             Kintone Base Url        [default: KINTONE_BASE_URL]
-u, --username             Kintone Username        [default: KINTONE_USERNAME]
-p, --password             Kintone Password        [default: KINTONE_PASSWORD]
--api-token            App's API token        [default: KINTONE_API_TOKEN] …
```
=> feat(data-loader): enhance CLI help message (type and requirement of arguments)

examples/rest-api-client-demo/src/app.ts, packages/rest-api-client/docs/app.md, packages/rest-api-client/src/client/AppClient.ts, packages/rest-api-client/src/client/__tests__/AppClient.test.ts, packages/rest-api-client/src/client/types/app/action.ts, packages/rest-api-client/src/client/types/app/index.ts, packages/rest-api-client/src/client/types/app/report.ts
Action Settings API was released in 2021 Mar update!
https://kintone.cybozu.co.jp/update/main/2021-03.html#point5
- Get Action Settings (`GET /k/v1/app/actions.json`)
- https://developer.kintone.io/hc/en-us/articles/900004690626
- Update Action Settings (`PUT /k/v1/preview/app/actions.json`)
- https://developer.kintone.io/hc/en-us/articles/900005635363
```sh
$ yarn build
$ cd examples/rest-api-client-demo
$ yarn run-script app getAppActions
$ yarn run-script app getAppActionsPreview
$ yarn run-script app updateAppActions
```
=> feat(rest-api-client): Support App Action Settings API

packages/data-loader/src/commands/export.ts, packages/data-loader/src/commands/import.ts, packages/data-loader/src/main.ts
In this PR, I apply accurated types to CLI command builder (`builder` function in `src/commands/*.ts`)
This resolves following problems.
- type inference does not work in command builder function because its parameter is `any`.
- type inference is breaking between `src/main.ts` and `src/commands/*.ts`bacause of using of `yargs.commandDir`.
This PR doesn't affect on runtime.
```sh
$ yarn build
$ yarn lint
$ yarn test
```
=> fix(data-loader): apply accurated types to CLI command builder

packages/dts-gen/src/cli-parser.test.ts, packages/dts-gen/src/cli-parser.ts
This introduces new warning messages for the deprecation of `--host`, `--proxyHost`, and `--proxyPort`.
We'll remove these options in the future, so we have to print warning messages for the options.
I've added deprecating messages for the usage of the options.
I've added tests for this, and you can test this by running the cli command of `dts-gen`.
=> feat(dts-gen): print deprecating messages for --host, --proxyHost, and --proxyPort

packages/data-loader/src/__tests__/api.test.ts, packages/data-loader/src/api.ts
According to https://developer.kintone.io/hc/en-us/articles/212494698#consideration, it announces that set an appropriate value in the User-Agent header.
I want that data-loader sets a custom User-Agent string.
set a custom User-Agent string as `data-loader@version`
`yarn test`
=> chore(data-loader): set a User-Agent string for data-loader

.github/workflows/test.yml, examples/rest-api-client-demo/package.json, packages/create-plugin/package.json, packages/customize-uploader/package.json, packages/data-loader/package.json, packages/dts-gen/package.json, packages/plugin-manifest-validator/package.json, packages/plugin-packer/package.json, packages/plugin-uploader/package.json, packages/profile-loader/package.json, packages/rest-api-client/package.json, packages/webpack-plugin-kintone-plugin/package.json
Node v10 is now in EOL, so we can remove supporting the version.
I've updated each engine version from v10 to v12 and have updated the versions for the `test` GitHub Actions.
This did not update any implementation, so I expected to be able to use `kintone/js-sdk` with Node v10.
But it won't work in the future.
=> chore: drop Node v10 support because of the EOL (BREAKING CHANGE)

packages/dts-gen/kintone.d.ts, packages/dts-gen/src/integration-tests/dts-gen-api-test.ts
`kintone.mobile.app.record.getFieldElement()` was released in 2020 Oct update!
- release note : https://kintone.cybozu.co.jp/update/main/2020-10.html#point7
- spec: https://developer.kintone.io/hc/en-us/articles/213148957/#record_getFieldElement
```sh
$ yarn build
$ yarn lint
$ yarn test
```
=> feat(dts-gen): Support `kintone.mobile.app.record.getFieldElement()`

packages/dts-gen/kintone.d.ts, packages/dts-gen/src/integration-tests/dts-gen-api-test.ts
`kintone.$PLUGIN_ID` is contained in `kintone` object, but dts-gen doesn't have the type definition of it currently.
> The variable kintone.$PLUGIN_ID will hold the Plug-in ID which will be needed.
https://developer.kintone.io/hc/en-us/articles/212495078-Steps-for-plug-in-development
```sh
$ yarn build
$ yarn lint
$ yarn test
```
=> feat(dts-gen): add type definition of `kintone.$PLUGIN_ID`

packages/data-loader/README.md, packages/data-loader/src/controllers/__tests__/export.test.ts, packages/data-loader/src/controllers/export.ts
We want to download attachment files of subtable when exporting records.
```sh
$ yarn build
$ node cli.js export --app=<APP_ID> --attachment-dir=foo # and username, password, base-url
```
=> feat(data-loader): export attachment files of subtable

packages/dts-gen/kintone.d.ts, packages/dts-gen/src/integration-tests/dts-gen-api-test.ts
[Get Space Element](https://developer.kintone.io/hc/en-us/articles/900006264623)  API was released in 2021 Apr update!
- release note: https://kintone.cybozu.co.jp/update/main/2021-04.html#point3
- spec: https://developer.kintone.io/hc/en-us/articles/900006264623
- Desktop: `kintone.space.portal.getContentSpaceElement()`
- Mobile: `kintone.mobile.space.portal.getContentSpaceElement()`
```sh
$ yarn build
$ yarn lint
$ yarn test
```
=> feat(dts-gen): Support Get Space Element API

packages/dts-gen/kintone.d.ts, packages/dts-gen/src/integration-tests/dts-gen-api-test.ts
`kintone.mobile.app.getFieldElements()` was released in 2020 Oct update!
- release note : https://kintone.cybozu.co.jp/update/main/2020-10.html#point6
- spec: https://developer.kintone.io/hc/en-us/articles/213148937/#getFieldElements
```sh
$ yarn build
$ yarn lint
$ yarn test
```
=> feat(dts-gen): Support `kintone.mobile.app.getFieldElements()`

packages/plugin-uploader/package.json
find a typo at `description` in `package.json`
fix typo
N/A
=> chore(plugin-uploader): fix typo in package.json

packages/data-loader/src/commands/export.ts, packages/data-loader/src/commands/import.ts
yargs/yargs#1928 is fixed by DefinitelyTyped/DefinitelyTyped#52624
This PR doesn't affect on runtime.
```sh
$ yarn build
$ yarn lint
$ yarn test
```
=> fix(data-loader): apply @types/yargs bugfix (DefinitelyTyped/DefinitelyTyped#52624)

packages/data-loader/src/__tests__/main.test.ts
some tests are flaky because of its long execution time.
I set 10,000 milliseconds as the new timeout duration (twice of the default).
```sh
$ yarn build
$ yarn test
```
=> test(data-loader): fix flaky tests by extending timeout

packages/plugin-uploader/package.json, yarn.lock
Fix #886.
It's just a temporary measure and we need to solve the actual cause of the problem,
but it seems to take a little time.
So I temporarily pinned the puppeteer version to v8, in which plugin-uploader works fine.
Pinned the puppeteer version to v8.
=> fix(plugin-uploader): pin puppeteer version to v8

packages/data-loader/README.md, packages/data-loader/src/commands/export.ts, packages/data-loader/src/controllers/__tests__/export.test.ts, packages/data-loader/src/controllers/export.ts
I want to export records which to sort by any field. 
- add `--order-by` option
- rename an export option as `--query` (`-q`) -> `--condition` (`-c`)
```shell
$ yarn build
$ node lib/main.js export --app APP_ID --order-by "Customer desc"
```
The result is sort by `Customer` field in descending order.
=> feat(data-loader): add `--order-by` of export option (BREAKING CHANGE)

packages/rest-api-client/src/http/AxiosClient.ts
Fix #915 .
When uploading large (> 10MB) file by `file.uploadFile()`, it throws an error.
Sample code:
```typescript
import { KintoneRestAPIClient } from "@kintone/rest-api-client";
const client = new KintoneRestAPIClient({ ... });
(async () => {
const result = await client.file.uploadFile({
file: { path: "./large-file.txt" },
});
console.log(result);
})();
```
Error:
```
(node:94564) UnhandledPromiseRejectionWarning: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
```
Set `maxBodyLength: Infinity` in Axios.
https://github.com/axios/axios#request-config
```bash
$ yarn build
$ cd examples/rest-api-client-demo
$ mkfile 10m foo.txt
$ yarn run-script file uploadFileByPath
```
=> fix(rest-api-client): set `maxBodyLength: Infinity` to avoid ERR_FR_MAX_BODY_LENGTH_EXCEEDED error

packages/rest-api-client/src/platform/browser.ts
Occured error "location undefined" at React Native.
React Nativeでlocation undefinedエラーが発生します。
If baseUrl is passed, location is not used.
baseUrlが渡された場合はlocationを利用しない。
Execute REST API from browser, Node, React Native.
ブラウザやNode、React NativeからREST APIを実行します。
=> fix(rest-api-client): `baseUrl` is not used when `location` is undefined

packages/customize-uploader/src/commands/index.ts
For impact to performance, we want to avoid uploading customize files in parallel.
upload customize files sequentially.
```shell
yarn build
bin/cli.js sample/customize-manifest.json
```
=> fix(customize-uploader): upload customize files sequentially

packages/data-loader/src/controllers/__tests__/export.test.ts, packages/data-loader/src/controllers/attachments.ts, packages/data-loader/src/controllers/export.ts
Refer to #950.
This PR resolves two tasks of #950.
- Design the format of the value of attachment file in JSON
- Consider duplicate name of attachments in the same field
- Attachment metadata will be written to `<attachment-dir>/attachments.json`
- Attachment schema is written in [attachment.ts](https://github.com/kintone/js-sdk/pull/887/files#diff-827e45a0ece2af288fafa1cb00e89dd8603b38cdbebecfed2f77cd4c49ea1af9)
- Duplicate file names in a record will be renamed with the index as `<original filename>-<index>.<extension>`
<details>
If the following records are exported,
```json
[
{
"Attachment_0": {
"type": "FILE",
"value": [
{
"fileKey": "...",
"name": "image.png",
"contentType": "image/png",
"size": "..."
},
{
"fileKey": "...",
"name": "image.png",
"contentType": "image/png",
"size": …
```
=> feat(data-loader): generate attachment metadata when export (JSON)

package.json
If I will check release notes of js-sdk, should check  CHANGELOG.md under each package.
Famous libraries such as React are often writing a release page in Github.
- https://github.com/facebook/react/releases/tag/v17.0.2
- https://github.com/almin/almin/releases/tag/almin%400.19.0
Use `--create-release` with `lerna publish`, Lerna creates a release page.
https://github.com/lerna/lerna/blob/main/commands/version/README.md#--create-release-type
⚠️ Please add your GitHub authentication token to the `GH_TOKEN` environment variable in your pc.
In a test repository, I executed `lerna publish --conventional-commits --create-release github`,  and I confirm created a release page.
=> chore: create release page with release

packages/customize-uploader/src/KintoneApiClient.ts, packages/customize-uploader/src/__tests__/util.test.ts, packages/customize-uploader/src/util.ts
Fixes #1009.
Even if specify `--proxy` option, customize-uploader is not using the value.
https://github.com/kintone/js-sdk/blob/a6c7ee5eb9ea3a0d647fe8cbec0f16667681295e/packages/customize-uploader/src/KintoneApiClient.ts#L53
pass the specified proxy value to KintoneRestAPIClient
1. Setup a proxy server using [Squid](http://www.squid-cache.org/).
The proxy server is `http://localhost:3128`
2. execute customize-uploader with proxy option
```shell
$ cd packages/customize-uploader
$ bin/cli.js sample/customize-manifest.json --proxy http://localhost:3128
```
=> fix(customize-uploader): pass the value of `--proxy`

packages/data-loader/src/controllers/__tests__/export.test.ts, packages/data-loader/src/controllers/attachments.ts, packages/data-loader/src/controllers/export.ts
With the current schema, attachments are stored in `<attachmentDir>/<record ID>/<filename>`,
but there is no record ID information in the metadata.
Refer #887 for the current schema.
In this PR, the leaf node will be changed.
- current: filename of attachment file
- new: relative path of attachment file from `attachments.json`
<details>
If the following records are exported,
```json
[
{
"Attachment_0": {
"type": "FILE",
"value": [
{
"fileKey": "...",
"name": "image.png",
"contentType": "image/png",
"size": "..."
},
{
"fileKey": "...",
"name": "image.png",
"contentType": "image/png",
"size": "..."
}
]
},
"Table_0": {
"type": "SUBTABLE",
"value": [
{
"id": "...",
"value": {
"添付ファイル": {
"type": "FILE",
"value": [
{
"fileKey": "...",
"name": "image.png",
"contentType": "image/png",
"size": …
```
=> fix(data-loader): fix attachment metadata schema

packages/plugin-uploader/package.json, packages/plugin-uploader/src/index.ts, yarn.lock
Over Puppeteer 9.x, fail to upload a plugin file.
Because Puppeteer has fixed `page.click()` method to be called sequentially the move, down, and up method.
Ref. https://github.com/puppeteer/puppeteer/pull/7097
On the other hand, Puppeteer 8.x fail to install in M1 mac.
Ref. https://github.com/puppeteer/puppeteer/issues/6622
click "Import" button inside `page.evaluate()` instead of `page.click()`
```
yarn build
cd packages/plugin-uploader
bin/cli.js sample-plugin.zip
```
=> fix(plugin-uploader): change the way of clicking the "Import" button

packages/data-loader/src/__tests__/main.test.ts
Fix #1023 .
move `jest.setTimeout` to top of the file.
I confirmed that `jest.setTimeout` works in modified code by the following steps:
- Replace `jest.setTimeout(30000)` to `jest.setTimeout(5)` (set very small timeout ms)
- Run `yarn test` under packages/data-loader
- The test fails and the error message says "Exceeded timeout of **5 ms** for a test."
```
FAIL  src/__tests__/main.test.ts (5.099 s)
● main › should throw error when no commands are passed
thrown: "Exceeded timeout of 5 ms for a test.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
26 |
27 | describe("main", () => {
> 28 |   it("should throw error when no commands are passed", () => {
|   ^
29 |     return checkRejectArg({
30 |       arg: "",
31 |       errorMessage: "Not …
```
=> test(data-loader): move `jest.setTimeout` to top of the file 

packages/plugin-uploader/README.md, packages/plugin-uploader/bin/cli.js, packages/plugin-uploader/src/index.ts, packages/plugin-uploader/src/messages.ts, packages/plugin-uploader/src/params.ts
The `--domain` option has been deprecated(https://github.com/kintone/js-sdk/pull/697), in this PR will remove the option.
remove to support `--domain` option and  `KINTONE_DOMAIN`
- If execute `bin/cli.js sample.zip` with `--base-url` option or `KINTONE_DOMAIN`, `--base-url` option is required.
=> refactor(plugin-uploader): remove `--domain` option and `KINTONE_DOMAIN` (BREAKING CHANGE)

packages/customize-uploader/README.md, packages/customize-uploader/bin/cli.js, packages/customize-uploader/src/KintoneApiClient.ts, packages/customize-uploader/src/commands/import.ts, packages/customize-uploader/src/commands/index.ts, packages/customize-uploader/src/messages.ts, packages/customize-uploader/src/params/index.ts
The `--domain` option has been deprecated(#602), in this PR will remove the option.
remove to support `--domain` option and  `KINTONE_DOMAIN`
- If execute `bin/cli.js sample/customize-manifest.json ` with `--base-url` option or `KINTONE_DOMAIN`, `--base-url` option is required.
=> refactor(customize-uploader): remove --domain option and KINTONE_DOMAIN (BREAKING CHANGE) 

packages/dts-gen/docs/maintenance-guide.md, packages/dts-gen/package.json, packages/dts-gen/src/cli-parser.test.ts, packages/dts-gen/src/cli-parser.ts, packages/dts-gen/src/integration-tests/setup-test-app.ts, packages/dts-gen/src/kintone/clients/axios-utils.test.ts, packages/dts-gen/src/kintone/clients/axios-utils.ts, packages/dts-gen/src/kintone/clients/forms-client-impl.test.ts
The `--host`, `--proxyHost` and `--proxyPort` options have been deprecated(#869), in this PR will remove the options.
remove to support following options.
- `--host`
- `--proxyHost`
- `--proxyPort`
If execute below command  with `--host` or `--proxyHost` or `--proxyPort`, an error occurs as missing the option.
```
$ npx ts-node src/index.ts --host https://xxx.cybozu.com --username *** --password *** --app-id 3
```
=> refactor(dts-gen): remove --host, --proxyHost and --proxyPort options (BREAKING CHANGE) 

packages/dts-gen/src/integration-tests/dts-gen-api-test.ts, packages/dts-gen/src/integration-tests/setup-test-app.ts, packages/dts-gen/src/kintone/clients/demo-datas.ts, packages/dts-gen/webpack.config.js
The integration-test  in dts-gen does not work cause of the following probrems:
Ref. https://github.com/kintone/js-sdk/issues/885
- The way of use has been changed in commander v7
Ref. https://github.com/tj/commander.js/releases/tag/v7.0.0
- No longer include a polyfill for this Node.js variable in webpack v5
Ref. https://webpack.js.org/migrate/5/#run-a-single-build-and-follow-advice
- Table field has added a label property
- migrate commander v8 and webpack 5
- add a label property into Table field
Execute the following commands.
```
$ cd packages/dts-gen
$ yarn build
$ node ./dist/integration-tests/setup-test-app.js --integration-test-js-file ./dist/dts-gen-integration-test.js
```
A kintone app is created in your kintone
Access the kintone app, this app includes 1 demo record data.
Edit …
=> test(dts-gen): fix broken setup-test-app and integration-test

package.json, packages/create-plugin/README.md, packages/create-plugin/package.json, packages/customize-uploader/README.md, packages/customize-uploader/package.json, packages/data-loader/README.md, packages/dts-gen/README.md, packages/plugin-manifest-validator/README.md, packages/plugin-manifest-validator/package.json, packages/plugin-packer/README.md, packages/plugin-packer/package.json, packages/plugin-uploader/README.md, packages/profile-loader/README.md, packages/rest-api-client/README.md, packages/webpack-plugin-kintone-plugin/README.md
The following points differ depending on package.
- `author` in package.json
- badge list in README.md
Unify the above.
N/A
=> chore: unify package badges

.github/workflows/release.yml, .github/workflows/version.yml
Because we don't want to release js-sdk packages from local machine anymore.
The release sequence is as follows.
N/A
=> build: release packages on GitHub Actions

package.json, yarn.lock
caniuse-lite db is outdated.
```shell
$ yarn build
...
@kintone/rest-api-client: Browserslist: caniuse-lite is outdated. Please run:
@kintone/rest-api-client: npx browserslist@latest --update-db
@kintone/rest-api-client: Why you should do it regularly:
@kintone/rest-api-client: https://github.com/browserslist/browserslist#browsers-data-updating
...
```
- new version: `1.0.30001298`
- old versions: `1.0.30001228`, `1.0.30001275`, `1.0.30001282`
```diff
Target browser changes:
- and_chr 95
+ and_chr 96
- and_ff 92
+ and_ff 95
- android 95
+ android 96
- chrome 93
- chrome 92
+ chrome 97
- edge 95
- edge 94
+ edge 97
+ edge 96
- firefox 93
- firefox 92
+ firefox 95
- ios_saf 15
+ ios_saf 15.2
+ ios_saf 15.0-15.1
- opera 80
- opera 79
+ opera 82
- safari 15
+ safari 15.2
```
```shell
$ yarn …
```
=> chore(deps): update caniuse-lite

packages/rest-api-client/package.json, packages/rest-api-client/rollup.config.js, packages/rest-api-client/src/__tests__/KintoneRequestConfigBuilder.test.ts, yarn.lock
[js-base64 v3.x](https://github.com/dankogai/js-base64/tags) is released
Update js-base64 to latest version.  The `yarn build` fails with the latest js-base64, so the generated script can include ES6 `const` and [ecma-version-validator](https://github.com/koba04/rollup-plugin-ecma-version-validator).  To prevent the issue, fix rollup config in rest-api-client as the following:
1. Transpile TypeScripts to ES6 by the babel plugin.
1. Resolve node modules by the node-resolve plugin.
1. Convert CommonJS modules to ES6 by the commonjs plugin
1. Transform ES6 to ES5 by the babel plugin.
=> chore(deps): update js-base64 to v3.x

packages/data-loader/src/printers/printAsCsv/__tests__/convertKintoneRecordsToCsv.test.ts, packages/data-loader/src/printers/printAsCsv/__tests__/fixtures/subtable_input_with_empty_table.json, packages/data-loader/src/printers/printAsCsv/convertKintoneRecordsToCsv.ts
When a Table's value is an empty array, exporting in csv format results in an empty row, even though there're values in fields outside the Table that I want to export.
This happens as Table value was always supposed to be non-empty.
※Table with value of an empty array is rare but not impossible. One way of reproducing this would be adding a Table to a kintone APP with existing records - the Table value for those records would be `[]`.
```sh
$ yarn build
$ yarn lint && yarn test
```
```sh
$ yarn build
$ node lib/main.js export --format="csv" --app <appId>
```
=> fix(data-loader): export csv correctly when Table value is empty array

.github/workflows/test.yml
Because yarn install randomly failed on workflows on windows runner via network timeout
```
Run yarn install
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-7.2.0.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "D:\\a\\js-sdk\\js-sdk\\yarn-error.log". …
```
=> ci: extend yarn network timeout

packages/data-loader/README.md, packages/data-loader/src/kintone/__tests__/fixtures/can_upload_files_in_subtable.ts, packages/data-loader/src/kintone/__tests__/upload.test.ts, packages/data-loader/src/kintone/upload.ts, packages/data-loader/src/parsers/parseCsv/isImportSupportedFieldType.ts
File upload and import are vital features for Data-loader users.
To upload and import local files by including a local file path in the original CSV/JSON file.
```
$ yarn build
$ yarn lint && yarn test
```
```
$ yarn build
$ node lib/main.js import --app <appId> --file-path <path-to-csv-file>
```
=> feat(data-loader): support import attachment field with subtable 

renovate.json
Because we hold renovate PRs requiring approval and auto-mergeable PRs are rate limited.
- extends [:prConcurrentLimitNone](https://docs.renovatebot.com/presets-default/#prconcurrentlimitnone)
N/A
=> chore: disable renovate rate limit

packages/rest-api-client/src/KintoneRestAPIClient.ts, packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts
When baseUrl with a trailing slash is given, generated request URL has a duplicated slash.
It causes an error when requesting to kintone.com environment.
e.g. with record.json...
- baseUrl: `https://example.kintone.com` => request URL: `https://example.kintone.com//k/v1/record.json` 🙆‍♂️ 
- baseUrl: `https://example.kintone.com/` =>  request URL: `https://example.kintone.com//k/v1/record.json` 🙅 
In this PR, remove the trailing slash from baseUrl internally.
Users still can use baseUrl with a trailing slash.
```
$ yarn build
$ yarn lint && yarn test
```
=> fix(rest-api-client): remove trailing slash from baseUrl internally

examples/rest-api-client-demo/package.json, packages/create-plugin/package.json, packages/customize-uploader/package.json, packages/webpack-plugin-kintone-plugin/package.json
`yarn run-script` in examples does not work.
Run examples by ts-node
Run the following in `examples/rest-api-client-demo` directory:
```
yarn run-script record getRecord
```
=> fix(examples): Run examples by ts-node

packages/plugin-packer/package.json, packages/plugin-packer/site/index.js, yarn.lock
close #1492 
Replace deprecated `createStore` with [`configureStore`](https://redux-toolkit.js.org/api/configureStore) provided by Redux Toolkit.
Run plugin-packer debug server by the following:
```
yarn workspace @kintone/plugin-packer start
```
then create a plugin on the site.
=> chore(plugin-packer): do not use deprecated api

.github/workflows/compile-data-loader-binary.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .github/workflows/yamory.yml, examples/rest-api-client-demo/package.json, packages/create-plugin/package.json, packages/customize-uploader/package.json, packages/data-loader/package.json, packages/dts-gen/package.json, packages/plugin-manifest-validator/package.json, packages/plugin-packer/package.json, packages/plugin-uploader/package.json, packages/profile-loader/package.json, packages/rest-api-client/package.json, packages/webpack-plugin-kintone-plugin/package.json
Node v12 has been in EOL since April 30th.
- from this PR, the oldest supported version is v14.
N/A
=> chore!: drop Node v12 support because of the EOL (BREAKING CHANGE)

packages/rest-api-client/src/__tests__/KintoneRestAPIClient.test.ts, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/types/global/index.d.ts
To fix type error.
Cast type as BlobPart
`yarn test`
=> chore(rest-api-client): fix type error for dom

.github/workflows/release.yml, .github/workflows/version.yml
When we release packages with release workflow, all packages have version bumps even if no changes.
workflow: https://github.com/kintone/js-sdk/actions/workflows/release.yml
log: https://github.com/kintone/js-sdk/runs/4849837084?check_suite_focus=true
Maybe it's because `actions/checkout@v2`fetches only the latest commit by default (lerna/lerna#2542 ).
fix it.
At the following commit, only the plugin-uploader has not been changed since the last release.
commit: https://github.com/kintone/js-sdk/tree/16734db15cb5ec56a8b86f2047a0b099af9bbac6/packages
Then the result of the `version` workflow is as follows.
plugin-uploader does not have version bumps.
version workflow: https://github.com/kintone/js-sdk/runs/6506285728?check_suite_focus=true
```
Changes:
- @kintone/rest-api-client-demo: 3.0.0 …
```
=> ci: fix version bumps of `release` workflow

.github/workflows/test.yml
vercel/pkg supports Node v18 on 5.7.0.
https://github.com/vercel/pkg/releases/tag/5.7.0
=> ci: add Node v18 to `test` workflow

.github/workflows/compile-data-loader-binary.yml, .github/workflows/license.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/version.yml, .github/workflows/yamory.yml
Reduce process time on CI (GitHub Actions).  We can cache yarn packages due to they are immutable. 
Reduce process time on CI (GitHub Actions).  We can cache yarn packages due to they are immutable.  It allows caching of global package data by internally using [actions/cache](https://github.com/actions/cache).
See CI results
=> chore: cache yarn packages on GitHub Actions

packages/webpack-plugin-kintone-plugin/src/index.ts
It is not necessary to use string literals for this purpose.
Use `this.name` instead of string literal
Running current tests.
=> Use `this.name` instead of string literal

packages/data-loader/README.md, packages/data-loader/src/commands/export.ts, packages/data-loader/src/commands/import.ts, packages/data-loader/src/printers/index.ts
Because when exporting/importing data to and from other services, CSV is more general than JSON.
```
node lib/main.js <options>
```
=> fix(data-loader)!: change default format from JSON to CSV

packages/rest-api-client/src/platform/browser.ts
fixes https://github.com/kintone/js-sdk/issues/934
N/A
=> fix(rest-api-client): throw an error if `location` is undefined on browser

.gitignore, packages/create-plugin/package.json, packages/create-plugin/src/__tests__/template.test.ts, packages/create-plugin/src/template.ts, packages/create-plugin/templates/modern/webpack.config.template.js, packages/create-plugin/templates/modern/webpack.entry.json
fixes https://github.com/kintone/js-sdk/issues/1742.
```shell
yarn install
yarn build
yarn test
cd packages/create-plugin
node ./bin/cli.js --template modern path/to/generate/plugin
```
=> fix(create-plugin): fix generation of the wepack.config.js of the modern template

packages/rest-api-client/src/error/KintoneAllRecordsError.ts, packages/rest-api-client/src/error/__tests__/KintoneAllRecordsError.test.ts
fixes https://github.com/kintone/js-sdk/issues/1703.
N/A
=> fix: the errorIndex of KintoneAllRecordsError is incorrect

packages/dts-gen/src/templates/template.ts
fixes https://github.com/kintone/js-sdk/issues/1743
```console
$ kintone-dts-gen \
--base-url https://******.kintone.com --app-id 1 --username ******** --password ******** \
-o /tmp/my-fields.d.ts
```
```console
$ ls /tmp/my-fields.d.ts
/tmp/my-fields.d.ts
$ ls ./tmp/my-fields.d.ts 
ls: ./tmp/my-fields.d.ts: No such file or directory
```
=> fix(dts-gen): dts-gen does not output with the absolute path

packages/rest-api-client/docs/errorHandling.md, packages/rest-api-client/src/error/KintoneAllRecordsError.ts, packages/rest-api-client/src/error/__tests__/KintoneAllRecordsError.test.ts
Currently, KintoneAllRecordsError calculates numOfProcessedRecords and numOfAllRecords internally to print an error message.
This information should be provided to upper errors as the object property.
N/A
=> feat(rest-api-client): add numOfProcessedRecords and numOfAllRecords to KintoneAllRecordsError

package.json, packages/create-plugin/package.json, packages/customize-uploader/package.json, packages/dts-gen/package.json, packages/plugin-manifest-validator/package.json, packages/plugin-packer/package.json, packages/plugin-uploader/package.json, packages/webpack-plugin-kintone-plugin/package.json
Fixes #1843 
```
yarn build
yarn fix
```
=> chore: support npm script to fix lint error for all packages

packages/rest-api-client/package.json, packages/rest-api-client/src/client/FileClient.ts, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/src/platform/index.ts, packages/rest-api-client/types/global/index.d.ts, yarn.lock
=> feat: support auto-detect MIME type for the browser platform

packages/create-plugin/README.md, packages/create-plugin/src/messages.ts
The new devnet will be released on February, and devnet url will be changed.
So, now we need to change to the new one.
| old | new |
| ---| --- |
| https://developer.cybozu.io/ | https://cybozu.dev/ |
N/A
=> docs(create-plugin): replacing devnet URL to new version link

renovate.json5
To use digest pinning but want to follow the action version tag on updating third party actions
- Specify version to third party actions
https://docs.renovatebot.com/modules/manager/github-actions/#additional-information
https://zenn.dev/roottool/scraps/5a73b98e88d4d1
N/A
=> ci: pin version of third party actions

packages/dts-gen/package.json, packages/dts-gen/src/kintone/clients/axios-utils.test.ts, packages/dts-gen/src/kintone/clients/axios-utils.ts, packages/rest-api-client/package.json, packages/rest-api-client/src/KintoneRequestConfigBuilder.ts, packages/rest-api-client/src/__tests__/KintoneRequestConfigBuilder.test.ts, packages/rest-api-client/src/http/HttpClientInterface.ts, yarn.lock
After upgrading Axios package to version 1.3.4 for rest-api-client and dts-gen #1763,
There is a critical issue with vercel/pkg package.
```
pkg/prelude/bootstrap.js:1872
throw error;
^
Error: Cannot find module '/snapshot/cli-kintone/node_modules/axios/dist/node/axios.cjs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
at resolveExports …
```
=> fix: downgrade axios to 0.27.2

.github/workflows/yamory.yml
Currently, we validate the yamory scan script with SHA512 checksum to detect falsification.
We store the checksum on the workflow’s environment variable because it's a possible situation where both script and checksum are falsified.
However, it makes CI fail when the yamory script is updated.
We cannot predict when the yamory script will be updated, So CI fails randomly in effect.
In https://github.com/kintone/cli-kintone/pull/295, we made the default workflow permission `read-only`.
So that yamory workflow can only read repository contents now.
Our repositories are public, so there is no risk in reading the repo.
Therefore, we can remove stored checksum and download checksum file on each CI run. 
- remove `YAMORY_YARN_SCRIPT_SHA512` env variable
See the result of the latest CI run. …
=> ci: stop using local checksum of yamory script

packages/dts-gen/src/index.ts
When an error is caught by the handler() function, the command exits with exit status 0, so I'm unable to do error handling from a parent process.
Specifically, I am calling kintone-dts-gen in a loop within my tool "Goqoo on kintone" as follows, and I want to judge if the dts file creation succeeded or failed.
https://github.com/goqoo-on-kintone/goqoo/blob/267c1fbbf87b80f52e4882a0955c8f10ee6e8a01/src/generator/dts/index.ts#L53-L84
An error is caught, ends with exit status other than 0.
I returned 2 because there was already a process that returned 1, but it can be anything other than 2.
```shell
$ kintone-dts-gen --base-url example.cybozu.com -u hoge -p fuga --app-id 0 # Failed
$ echo $? # Before:0 / After:2
```
=> An error is caught, ends with exit status 1

packages/rest-api-client/DEPENDENCIES, packages/rest-api-client/package.json, packages/rest-api-client/rollup.config.mjs, yarn.lock
Currently, the UMD distribution of @kintone/rest-api-client does not follow the conditions of the third-party licenses.
N/A
=> chore(rest-api-client): bundle license to UMD file

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/version.yml, .github/workflows/yamory.yml, examples/rest-api-client-demo/package.json, packages/create-plugin/package.json, packages/customize-uploader/package.json, packages/dts-gen/package.json, packages/plugin-manifest-validator/package.json, packages/plugin-packer/package.json, packages/plugin-uploader/package.json, packages/profile-loader/package.json, packages/rest-api-client/package.json, packages/webpack-plugin-kintone-plugin/package.json
Node v14 has been in EOL since April 30th in 2023.
- drop Node v14 from the engines of each packages.
- From this PR, the oldest supported version is v16.
- update Node version in CI ([14, 16, 18] → [16, 18, 20])
N/A
=> build: drop Node v14 support because of the EOL

packages/dts-gen/docs/field-type-definition-guide.md, packages/dts-gen/src/cli-parser.ts, packages/dts-gen/src/index.ts, packages/dts-gen/src/templates/converter.ts, packages/dts-gen/src/templates/expressions/namespace.ts, packages/dts-gen/src/templates/template.ts, packages/dts-gen/src/types/template.ts, packages/dts-gen/src/validators/__tests__/args.test.ts, packages/dts-gen/src/validators/args.ts
An unclear message is shown when specifying an invalid `namespace` or `type-name` option.
For example:
```
$ kintone-dts-gen --base-url https://*****.cybozu-dev.com -u ****** -p ****** --app-id 1 --type-name SampleFields --namespace sample-fields
```
** Invalid `namespace`: `sample-fields`
** Valid `namespace`: `sampleFields`
Current error message:
```
Error: failed to fix lint errors on generated type definition file.
at /Users/h000953/Development/js-sdk/packages/dts-gen/dist/templates/template.js:61:15
at Generator.next (<anonymous>)
at fulfilled (/Users/h000953/Development/js-sdk/packages/dts-gen/dist/templates/template.js:28:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Run command
```
$ kintone-dts-gen --base-url https://*****.cybozu-dev.com -u …
```
=> fix(dts-gen): validate namespace and typename

packages/rest-api-client/package.json, packages/rest-api-client/rollup.config.mjs, packages/rest-api-client/src/platform/browser.ts, packages/rest-api-client/tsconfig.json, yarn.lock
Fixes #2111 
- Return version from package.json instead of hardcode PACKAGE_VERSION
N/A
=> fix(rest-api-client): return version from package.json instead of hardcode

packages/create-plugin/tsconfig.json
The `include` of the tsconfig of the create-plugin has typo to `indlude`.
- fix type `indlude` to `include`
- remove `exclude` that is unnecessary
N/A
=> fix(create-plugin): fix `include` of tsconfig

packages/dts-gen/docs/how-to-use.md
Currently, the document of the dts-gen guide to add `files`, `include`, and `exclude` to tsconfig.json.
However, `exclude` is to filter out some files from the result of `include`, so that is unnecessary in this case.
> exclude only changes which files are included as a result of the include setting.
https://www.typescriptlang.org/tsconfig#include
https://www.typescriptlang.org/tsconfig#exclude
- remove `exclude` from tsconfig of the document
N/A
=> fix(dts-gen): remove unnecessary `exclude` from tsconfig

packages/plugin-uploader/src/index.ts
- Fix the warning message of Puppeteer package
- Avoid trouble in near future
- Add new Headless mode as default
- Run plugin-uploader without warning message
=> fix: Ignore warning message in puppeteer

packages/rest-api-client/package.json, packages/rest-api-client/rollup.config.mjs, pnpm-lock.yaml
Some packages are deprecated, or the current version is deprecated.
N/A
=> build: replace deprecated packages

.github/workflows/release.yml
CI Checks do not run when the release pull request is created/updated.
N/A
=> ci: trigger CI checks for release PR

packages/plugin-manifest-validator/src/__tests__/index.ts, packages/plugin-manifest-validator/src/index.ts
- New default non-existent file message will be more directive than the current message.
- Update default message to "file should exist (`${filePath}`)"
=> fix(plugin-manifest-validator): update default non-existent file message

.github/workflows/test.yml
Node 20.6 has just been released on 2023-09-04, [ref](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2023-09-04-version-2060-current-juanarbol-prepared-by-ulisesgascon)
Node 20.6 breaks Babel, and Babel breaks our tools, [ref](https://github.com/babel/babel/issues/15927)
```
pnpm build && pnpm test
```
=> ci: harde code to Node 20.5 until Node 20.6 is fixed

.github/workflows/test.yml, release-please-config.json
In pnpm, `pnpm-lock.yaml` is also updated when a dependent package in the workspace is updated.
Our release tool, `release-please`, doesn't update `pnpm-lock.yaml` in its release PR.
So, there is a mismatch version between `pnpm-lock.yaml` and `package.json`. [ref](https://github.com/kintone/js-sdk/actions/runs/6073131863/job/16474457528?pr=2227)
```
Run pnpm install --frozen-lockfile
Scope: all 11 workspace projects
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with packages/customize-uploader/package.json
Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
Failure reason:
specifiers in the lockfile …
```
=> ci: remove node-workspace in release-please

.github/workflows/test.yml
- Make the test workflow always tests with the latest version of Node 20
- Revert to Node 20.x in test ci workflow
- N/A
=> ci: change Node version from 20.5 to 20.x in test CI workflow

examples/rest-api-client-demo/package.json, pnpm-lock.yaml
We disabled plugin node-workspace in release-please ([ref](https://github.com/kintone/js-sdk/pull/2263)). Therefore, the version of the private package is not updated automatically in dependent packages. This leads to the issue mismatch version on Github Action.
Ref: https://github.com/kintone/js-sdk/actions/runs/6526189211/job/17719679697
- Using [workspace protocol](https://pnpm.io/workspaces#workspace-protocol-workspace) for private packages.
```
pnpm install
```
=> fix(rest-api-client-demo): mismatch version of private package

packages/rest-api-client/package.json
- We can use rest-api-client on modern environment with moduleResolution: bundler
- Add types to the exports field in rest-api-client/package.json
- Follow the reproduction in [this issue](https://github.com/kintone/js-sdk/issues/2277)
=> fix(rest-api-client): Fix type resolution error on `moduleResolution: bundler`

.github/workflows/test.yml
GitHub provides macos runner.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
- Adding macOS runner for test workflow
```
pnpm build && pnpm test
```
=> ci: adding macOS runner for test workflow

.github/workflows/release.yml
- Replace deprecated octoken-action with built-in github action (create-github-app-token) to make our tool well maintainance.
- Replace deprecated octoken-action with built-in create-github-app-token in release.yml
- Demo repo:
https://github.com/tuanpham-playground/js-sdk-create-github-app-token/actions/runs/6571307859/job/17850207216
( check with peter-evans/create-or-update-comment@v3 )
=> ci: Replace `octoken-action` by `create-github-app-token`

.github/workflows/license.yml
The runner of the license workflow is using the specific version (ubuntu-20.04), not the latest version.
There is no issue with the latest version.
- Use ubuntu-latest runner for license workflow
N/A
=> ci: using ubuntu-latest runner for the license workflow

.github/workflows/release.yml
- Replace deprecated octoken-action with built-in github action (create-github-app-token) to make our tool well maintenance.
- Replace deprecated octoken-action with built-in create-github-app-token in release.yml
- Demo repo:
https://github.com/tuanpham-playground/js-sdk-create-github-app-token/actions/runs/6571307859/job/17850207216
( check with peter-evans/create-or-update-comment@v3 )
=> ci: Replace octoken-action by create-github-app-token 

packages/rest-api-client/src/__tests__/e2e.vite.test.ts
There is an issue with Vite e2e test case.
- Skip Vite test while investigating
```
pnpm test
```
=> test(rest-api-client): skip Vite test for investigating

packages/plugin-uploader/README.md, packages/plugin-uploader/src/cli.ts
`--waiting-dialog-ms` option is missed in Readme
- Add `--waiting-dialog-ms` option into Readme
- Update the description of `--waiting-dialog-ms` option 
N/A
=> chore(plugin-uploader): Add --waiting-dialog-ms option to Readme

packages/rest-api-client/docs/record.md
The error occurs when using getAllRecordsWithOffset with an application containing more than 10,000 records
Add warning message in Readme of getAllRecordsWithOffset
N/A
=> chore(rest-api-client): Add warning message in Readme of getAllRecordsWithOffset

packages/plugin-packer/package.json, pnpm-lock.yaml
A vulnerability issue of browserify-sign from version >= 2.6.0 and <= 4.2.1
Ref: https://github.com/kintone/js-sdk/security/dependabot/72
- Temporary using the non-vulnerability version of browserify-sign 4.2.2
N/A
=> fix(plugin-packer): Fix the vulnerability issue from browserify-sign

package.json, pnpm-lock.yaml
- Resolve vulnerability of follow-redirects package
- Use **overrides** property of pnpm in package.json to replace `follow-redirects` package if its version is lower 1.15.5
```
$ pnpm install
$ pnpm audit
```
=> fix: override follow-redirects package to resolve vulnerability

packages/dts-gen/kintone.d.ts
Missing the type NULL on the error property
- Adding the type NULL on the error property
N/A
=> fix(dts-gen): adding type NULL to the error property

packages/dts-gen/kintone.d.ts
The `error` property is not available on the below fields ([ref](https://kintone.dev/en/docs/kintone/js-api/events/event-object-actions/)).
- Record number
- Created datetime
- Updated datetime
- The `error` property is removed for the below fields
- Record number
- Created datetime
- Updated datetime
=> fix(dts-gen): remove unavailable property

packages/create-plugin/src/__tests__/fixtures/manifest.json, packages/create-plugin/src/manifest.ts, packages/create-plugin/templates/minimum/.eslintrc.js, packages/create-plugin/templates/minimum/src/js/config.js, packages/create-plugin/templates/minimum/src/js/desktop.js, packages/create-plugin/templates/minimum/src/js/mobile.js
- jQuery is the old technology, so we don't recommend using jQuery in new projects anymore.
- We will stop using jQuery in our minimum template.
- Remove jQuery from the minimum template
- The create-plugin can generate a plugin project with an updated minimum template (without jQuery code inside)
=> chore!(create-plugin): remove jQuery from the minimum template

.github/workflows/release.yml
1) release-please use a manifest configuration file by default. Therefore, we do not need to specify the `command` option.
2) The behavior of `releases_created` is changed from v3->v4, [ref](https://github.com/google-github-actions/release-please-action/issues/912)
- Remove the `command` option.
- Update the condition of `releases_created`
N/A
=> ci: resolve release-please-action warning

package.json, packages/plugin-packer/package.json, pnpm-lock.yaml
`browserify-sign` is added to plugin-packer as devDependencies. But, we don't use it directly.
- Remove the devDependencies `browserify-sign`
- Add it to `pnpm.overrides` property.
```
pnpm audit
```
=> chore(plugin-packer): move browserify-sign to pnpm overrides

examples/rest-api-client-demo/README.md, examples/rest-api-client-demo/package.json
- Our tools need support most common package managers
- Add npm, pnpm support in rest-api-client-demo
yarn
```
$ cd <path-to-rest-api-client-demo>
$ yarn demo space getSpace
$ yarn deploy
```
npm
```
$ cd <path-to-rest-api-client-demo>
$ npm run demo space getSpace
$ npm run deploy
```
pnpm
```
$ cd <path-to-rest-api-client-demo>
$ pnpm demo space getSpace
$ pnpm deploy
```
=> fix(rest-api-client-demo): add npm, pnpm support in rest-api-client-demo

examples/rest-api-client-demo/src/space.ts, packages/rest-api-client/docs/space.md, packages/rest-api-client/src/client/BaseClient.ts, packages/rest-api-client/src/client/SpaceClient.ts, packages/rest-api-client/src/client/__tests__/SpaceClient.test.ts, packages/rest-api-client/src/client/types/index.ts, packages/rest-api-client/src/client/types/space/index.ts
- Support `addSpaceFromTemplate` method to be able to add a new Space from Space Template.
- Add new method `addSpaceFromTemplate`
- Check test spec
=> feat(rest-api-client): add `space.addSpaceFromTemplate()` method

.github/workflows/license.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/yamory.yml
There is a new version of pnpm/action-setup v3. This version runs on Nodejs 20.
- Upgrade pnpm/action-setup to v3
N/A
=> ci: upgrade pnpm/action-setup to v3

packages/webpack-plugin-kintone-plugin/src/__tests__/cli.test.ts
- Fix fail test on Windows
- Following the 18.20.2/20.12.2 node.js releases, it is no longer valid to call child_process.spawn with a .cmd or .bat file without using the shell: true option.
Ref: https://nodejs.org/en/blog/release/v18.20.2
- Add `shell: true` to `spawnSync` configuration if OS is Windows.
`pnpm test`
=> test(webpack-plugin-kintone-plugin): fix failed test on windows

packages/rest-api-client/README.md
unpkg.com is maintained by a small team and was out of service recently.
Cybozu has its own CDN, Cybozu CDN, and we are providing a rest-api-client UMD file there.
https://cybozu.dev/ja/kintone/sdk/library/cybozu-cdn/#kintone-rest-api-client
- Replace CDN link from unpkg.com to Cybozu CDN
N/A
=> docs(rest-api-client): update CDN link from unpkg to Cybozu CDN

packages/create-plugin/__e2e__/e2e.test.ts, packages/create-plugin/src/messages.ts, packages/create-plugin/src/qa.ts
- Increase the reliability of create-plugin package.
- Add test case JsSdkTest-2, JsSdkTest-3
`pnpm test:e2e`
=> test(create-plugin): add test cases for JsSdkTest-2,3

packages/create-plugin/__e2e__/e2e.test.ts, packages/create-plugin/__e2e__/fixtures/index.ts, packages/create-plugin/__e2e__/fixtures/languageEN.ts, packages/create-plugin/__e2e__/fixtures/languageJA.ts, packages/create-plugin/__e2e__/fixtures/minimumTemplate.ts, packages/create-plugin/__e2e__/fixtures/modernTemplate.ts, packages/create-plugin/__e2e__/utils/CreatePlugin.ts, packages/create-plugin/__e2e__/utils/executeCommand.ts, packages/create-plugin/__e2e__/utils/generateWorkingDir.ts, packages/create-plugin/__e2e__/utils/helper.ts, packages/create-plugin/__e2e__/utils/verification.ts
- Increase the reliability of create-plugin package.
- Add test case JsSdkTest-5, JsSdkTest-6, JsSdkTest-7, JsSdkTest-8
`pnpm test:e2e`
=> test(create-plugin): add test cases for JsSdkTest-5,6,7,8

packages/create-plugin/__e2e__/e2e.test.ts, packages/create-plugin/__e2e__/fixtures/forbiddenCharacters.ts, packages/create-plugin/src/index.ts, pnpm-lock.yaml
When an error occurs, the exit code is returned as zero.
It's difficult to know whether the command is successful or not.
- The `exit-code` should be non-zero when an error occurs.
```
pnpm build
pnpm test:e2e
```
=> fix(create-plugin): exit-code should be non-zero when an error occurs

packages/dts-gen/src/templates/template.ts
- Fix error when running dts-gen globally
- Set current working directory to Eslint
`kintone-dts-gen --base-url <domain-name> -u <username> -p <password> --app-id <app-id> --type-name SampleFields --namespace abc.types -o sample-fields.d.ts`
Check command running locally and globally successful.
=> fix(dts-gen): fix error when running dts-gen globally

.github/workflows/release.yml
- The google-github-actions/release-please-action repo has been transferred to googleapis/release-please-action
https://github.com/googleapis/release-please-action/issues/980
- Use googleapis/release-please-action instead of google-github-actions/release-please-action
- Check release PR is created by the action
=> ci: Use googleapis/release-please-action instead of google-github-actions/release-please-action

packages/plugin-packer/package.json, packages/plugin-packer/src/cli.ts, packages/plugin-packer/src/console.ts, packages/plugin-packer/test/cli.spec.ts, pnpm-lock.yaml
Now, `plugin-manifest-validator` returns warnings if any. They should be printed on the console.
- Prints warning messages that are returned from `plugin-manifest-validator`.
N/A
=> feat(plugin-packer): print warning messages

packages/create-plugin/src/__tests__/fixtures/manifest.json, packages/create-plugin/src/manifest.ts, packages/plugin-manifest-validator/README.md, packages/plugin-manifest-validator/examples/manifest.json
In https://github.com/kintone/js-sdk/pull/2781 and https://github.com/kintone/js-sdk/pull/2782, we added the recommended URL to the JSON Schema file for the plugin manifest file.
That URL points to the `main` branch of this repository and potentially becomes a broken link if we change the directory structure. In this PR, we update the URL to point to the specific tag on this repo to make the URL more stable.
NOTE: We also plan to host schema files on the stable website.
- updated the URL
Check CI
=> fix: update plugin `manifest-schema.json` URL

pnpm-lock.yaml
- CI failed on main branch. The reason is pnpm-lock.yaml that has conflict version of deps.
- Resolve conflict version of pnpm-lock.yaml
- CI is green
=> chore(deps): update pnpm-lock.yaml

packages/create-plugin/__e2e__/e2e.test.ts, packages/create-plugin/__e2e__/utils/CreatePlugin.ts, packages/create-plugin/__e2e__/utils/executeCommand.ts
- The test cannot exit when exceeds the Jest timeout due to the spawn process.
- The execution time is too high.
- Teardown spawn process when a test case is finished
- Reduce the execution time
```
pnpm test:e2e
```
=> test(create-plugin): optimizing e2e test

examples/rest-api-client-demo/src/space.ts, packages/rest-api-client/docs/space.md, packages/rest-api-client/src/client/SpaceClient.ts, packages/rest-api-client/src/client/__tests__/SpaceClient.test.ts
Support addThread method to be able to add a tread to a space.
- Add new method addThread
Check test spec
=> feat(rest-api-client): add space.addThread() method

examples/rest-api-client-demo/src/app.ts, packages/rest-api-client/docs/app.md, packages/rest-api-client/src/client/AppClient.ts, packages/rest-api-client/src/client/__tests__/AppClient.test.ts, packages/rest-api-client/src/client/types/app/index.ts, packages/rest-api-client/src/client/types/app/plugin.ts
Support app.getPlugins method to be able to get the list of Plug-ins added to an App.
- Add new methods, app.getPlugins
- When I run pnpm fix, I faced the warning as below in AppClientTest:
`Arrow function has too many statements (41). Maximum allowed is 40  max-statements`
So I implemented the new unit tests separately from the existing root description method.
- Add type for AppPlugin
- Add and Fix doc
- I found a minor writing error in the doc of the getActions method, so I fixed it together.　 c4d753892db71e7a4c21077ed65e49c528b535d6
- The Lang type split into AppLang and PluginLocale because they are different.
Check test spec.
=> feat(rest-api-client): add app.getPlugins method

examples/rest-api-client-demo/src/app.ts, packages/rest-api-client/docs/app.md, packages/rest-api-client/src/client/AppClient.ts, packages/rest-api-client/src/client/__tests__/AppClient.test.ts
The method name moveToSpace can be misleading.
In fact, it not only changes the space, but also removes the space.
- change the `moveToSpace` method name to `move`
=> fix(rest-api-client): rename moveToSpace method to move

renovate.json5
The commit type for updating deps is fix, but we don't want to do this because it shows up as Bug Fixes in the release notes.
Change the commit type from `fix` to `chore`.
=> chore: change commit type from fix to chore

packages/rest-api-client/docs/plugin.md, packages/rest-api-client/src/client/PluginClient.ts, packages/rest-api-client/src/client/__tests__/PluginClient.test.ts, packages/rest-api-client/src/client/types/index.ts, packages/rest-api-client/src/client/types/plugin/index.ts
- Support plugin.getApps method to be able to get the list of Apps  that have the specified plug-in added.
- Add a document for the new methods.
- Add type for the new method request and response.
1. prepare installed plug-ins and add a plug-in to some apps.
```ts
const pluginId = (await client.plugin.getPlugins({
offset: 0,
limit: 1
})).plugins[0].id;
console.log(await client.plugin.getApps({
id: pluginId,
}));
```
=> feat(rest-api-client): add the method of plugin.getApps

packages/rest-api-client/docs/app.md, packages/rest-api-client/src/client/AppClient.ts, packages/rest-api-client/src/client/__tests__/app/Plugins.test.ts
- Support app.addPlugins method to be able to add Plug-ins to an App.
- Add a document for the new methods.
1. prepare installed plug-ins and apps in Kintone.
```ts
const pluginId = (await client.app.getPlugins({app: 1})).plugins[0].id;
console.log(await client.app.getPlugins({app: 2, preview: true}));
console.log(await client.app.addPlugins({app: 2, ids: [pluginId]}));
console.log(await client.app.getPlugins({app: 2, preview: true}));
```
=> feat(rest-api-client): add the method of app.addPlugins

packages/rest-api-client/docs/plugin.md, packages/rest-api-client/src/KintoneRestAPIClient.ts, packages/rest-api-client/src/client/PluginClient.ts, packages/rest-api-client/src/client/__tests__/PluginClient.test.ts, packages/rest-api-client/src/client/__tests__/SpaceClient.test.ts, packages/rest-api-client/src/client/types/index.ts, packages/rest-api-client/src/client/types/plugin/index.ts
- Support plugin.getPlugins method to be able to get the list of plug-ins imported into Kintone.
- Support plugin.getRequiredPlugins method to be able to get the list of plug-ins that have been deleted from Kintone, but have already been added to Apps.
- Support plugin.getApps method to be able to get the list of Apps that have the specified plug-in added. ([#2900](https://github.com/kintone/js-sdk/pull/2900))
- Add a document for the new methods.
- Add type for Plugin
NOTE: This PR also includes plugin.getApps (https://github.com/kintone/js-sdk/pull/2900)
1. prepare installed plug-ins and required plug-ins in Kintone.
```ts …
```
=> feat(rest-api-client): add plugin.getPlugins, getRequiredPlugins, and getApps

packages/rest-api-client/docs/plugin.md, packages/rest-api-client/src/client/PluginClient.ts, packages/rest-api-client/src/client/__tests__/PluginClient.test.ts, packages/rest-api-client/src/client/types/plugin/index.ts
- Support plugin.updatePlugin method to be able to update an imported plug-in in the Kintone environment.
- Add a document for the new method.
1. prepare a zip file for a plug-in and installe it in Kintone.
```ts
const fileKey = (await client.file.uploadFile({
file: {
path: "./files/plugin.zip"
}
})).fileKey;
if (typeof fileKey == "string") {
const pluginId = (await client.app.getPlugins({app: 42})).plugins[0].id;
console.log(await client.plugin.updatePlugin({id: pluginId, fileKey: fileKey}));
console.log(await client.app.getPlugins({app: 42, preview: true}));
}
```
=> feat(rest-api-client): add method of plugin.updatePlugin

packages/rest-api-client/docs/plugin.md, packages/rest-api-client/src/client/PluginClient.ts, packages/rest-api-client/src/client/__tests__/PluginClient.test.ts, packages/rest-api-client/src/client/types/plugin/index.ts
- Support plugin.installPlugin method to be able to install an imported plug-in in the Kintone environment.
- Add a document for the new method.
1. prepare a zip file for a plug-in and upload it in Kintone.
```ts
const fileKey = (await client.file.uploadFile({
file: {
path: "./files/plugin.zip"
}
})).fileKey;
if (typeof fileKey == "string") {
console.log(await client.plugin.installPlugin({fileKey: fileKey}));
}
```
=> feat(rest-api-client): add method of plugin.installPlugin

packages/rest-api-client/docs/plugin.md, packages/rest-api-client/src/client/PluginClient.ts, packages/rest-api-client/src/client/__tests__/PluginClient.test.ts, packages/rest-api-client/src/client/types/plugin/index.ts
- Support plugin.uninstallPlugin method to be able to uninstalls a plug-in from the Kintone environment.
- Add a document for the new method.
1. prepare a zip file for a plug-in.
```ts
// Upload a file and attach it to a record
const resp = await client.file.uploadFile({
file: {
path: "./files/plugin.zip"
}
});
const fileKey = resp.fileKey;
console.log(fileKey);
if (typeof fileKey == "string") {
const pluginId = (await client.plugin.installPlugin({fileKey: fileKey})).id;
console.log(pluginId);
console.log(await client.plugin.getPlugins({}));
await client.plugin.uninstallPlugin({id: pluginId});
console.log(await …
```
=> feat(rest-api-client): Add method for uninstall plugin

packages/plugin-uploader/src/params.ts
env variable should not be empty.
The isSet function check to see if the env value is a type string; however, in the cli flags for the env are all defined as type string defeating the purpose of the isSet function. This results in not prompting the user to fill out the necessary values to run the kintone plugin uploader. The code will throw an error. This is a bug.
I have updated the code to also check the value of the env. If the value is an empty string, isSet will return false.
Run the kintone plugin uploader without initializing env variables. Then see if the code will prompt the user.
=> fix(plugin-uploader): System ENV value check

.github/workflows/lint_pr.yml
Currently, all commits in the PR branch cannot be merged unless they follow Conventional Commits.
However, since we are using Squash Merge, it is sufficient if the PR title is a Conventional Commit, so the current rule is excessive.
Added GitHub Action to check PR Title.
see: https://github.com/amannn/action-semantic-pull-request
The following settings are required.
> Setting > General > Pull Requests
- Allow squash merging のみチェックする
- Default commit messageをPull Request Titleに変更
> Setting > Rules > Rulesets
- Targetsをinclude default branch
- Require status checks to passを有効にし、Validate PR Titleを追加する
https://github.com/user-attachments/assets/b8027ea1-7c46-40b7-a90a-a0d43632a7a2
=> ci: check conventional commits

packages/dts-gen/docs/field-type-definition-guide.md, packages/dts-gen/src/validators/__tests__/args.test.ts, packages/dts-gen/src/validators/args.ts
ref. #3035
Supported to use Japanese in version 5, but error in version 8.
```sh
$ npx -p @kintone/dts-gen@5 kintone-dts-gen --app-id 12 --type-name 'App取引先Fields'
```
```sh
$ npx -p @kintone/dts-gen@8 kintone-dts-gen --app-id 12 --type-name 'App取引先Fields'
Invalid type-name option!
The namespace and type-name convention:
- Starts with a letter (`a-z` or `A-Z`), underscore (`_`), or dollar sign (`$`).
- Can be followed by any alphanumeric, underscores, or dollar signs.
```
This pull request will enable the use of Japanese in `typename`.
Look at diff in args.test.ts.
=> feat(dts-gen): Characters check for typename compliant with ECMA262.

packages/dts-gen/src/templates/template.test.ts, packages/dts-gen/src/templates/template.ts
ref. #3059
I installed and ran the package and got an error `Error: Could not find config file.`.
I fixed to not read eslint.config, when using ESLint in running dts-gen, 
```sh
js-sdk/packages/dts-gen$ pnpm build
js-sdk/packages/dts-gen$ rm eslint.config.mjs
js-sdk/packages/dts-gen$ rm ../../eslint.config.mjs
js-sdk/packages/dts-gen$ ls fields.d.ts 
ls: 'fields.d.ts' にアクセスできません: そのようなファイルやディレクトリはありません
js-sdk/packages/dts-gen$ direnv exec . node dist/index.js --app-id 4 --type-name App顧客リストFields
js-sdk/packages/dts-gen$ ls fields.d.ts 
fields.d.ts
```
=> fix(dts-gen): Fix to not read eslint.config

packages/plugin-manifest-validator/README.md, packages/plugin-manifest-validator/examples/manifest.json, packages/plugin-manifest-validator/manifest-schema.d.ts, packages/plugin-manifest-validator/manifest-schema.json, packages/plugin-manifest-validator/src/__tests__/index.ts
- Added zh-TW, pt-BR, and th to the supported locales
link `@kintone/plugin-manifest-validator`
```
$ cd packages/plugin-manifest-validator
$ pnpm link --global
$ cd /path/to/test  # サンプルコードを実行するディレクトリで以下を実行
$ pnpm init
$ pnpm link --global @kintone/plugin-manifest-validator
```
Create a manifest that includes zh-TW, pt-BR, and th, and check that it passes validation.
```
const validator = require("@kintone/plugin-manifest-validator");
const manifest = {
manifest_version: 1,
version: 1,
type: "APP",
name: {
ja: "サンプルプラグイン",
en: "sample plugin",
zh: "插件的例子",
"zh-TW": "插件的例子",
es: "complemento de muestra",
"pt-BR": "complemento de amostra",
th: "ปลั๊กอินตัวอย่าง",
},
description: {
ja: "これはサンプルプラグインです。",
en: "This is sample plugin.",
zh: "这是插件的例子",
"zh-TW": "這是插件的例子",
es: "Este es un …
```
=> feat(plugin-manifest-validator): add locales

packages/rest-api-client/src/client/types/app/setting.ts
Revise the `titleField` type definition to ensure it correctly accommodates both selection modes, enhancing type safety in the application settings.
=> fix(rest): Separate titleField type between GET and UPDATE

packages/rest/src/client/Middlewares/HttpMethodOverrideMiddleware.ts, packages/rest/src/client/index.ts
`@kintone/rest-api-client` has the function to send a request with the `X-Http-Method-Override` header when the URL length is above 4096, but `@kintone/rest` doesn't yet have it.
Add a middleware for the same task.
1. Set the `THRESHOLD_AVOID_REQUEST_URL_TOO_LARGE` value 1.
2. send GET request.
3. check headers and HTTP method.
=> feat(rest): add HttpMethodOverrideMiddleware

packages/rest/package.json, packages/rest/vite.config.ts, pnpm-lock.yaml
The import/require target was incorrectly transformed on Vite output.
The output results are as follows.
```js
require(“/Users/tasshi/git/cybozu/js-sdk/node_modules/.pnpm/undici@7.4.0/node_modules/undici/index.js”)
```
- The local absolute path is specified.
- The entry point on the ESM side is specified
This is because Vite builds code for the browser.
(Browsers cannot import with the package name like `undici`, so Vite replaces it with the absolute path.)
By enabling SSR build, the build target is switched to Node.js, and the npm package name is retained.
```js
require(“undici”);
```
- enable SSR build for ESM/CJS build
ref. https://vite.dev/config/build-options.html#build-ssr
=> build(rest): enable SSR build to correct import target

packages/dts-gen/package.json, packages/rest-api-client/package.json, packages/rest-api-client/src/client/__tests__/File.test.ts, pnpm-lock.yaml
A critical security vulnerability (CVE-2025-7783) was discovered in the form-data npm package.
This vulnerability uses unsafe random number generation (Math.random()) for multipart form boundaries, which could allow attackers to predict boundaries and inject additional parameters into requests.
With a CVSS score of 9.4, this could potentially allow arbitrary requests to internal systems.
Updated both axios and form-data packages to their latest secure versions:
- axios: 1.8.4 → 1.12.2
- form-data: 4.0.1 → 4.0.4 (patched version for CVE-2025-7783)
These updates were applied to:
- packages/dts-gen/package.json
- packages/rest-api-client/package.json
- Updated test mocking in packages/rest-api-client/src/client/__tests__/File.test.ts for compatibility
The unit tests are passing, but could …
=> fix: bump axios and form-data npms for CVE-2025-7783
